xls/passes/bdd_simplification_pass.cc, xls/passes/bdd_simplification_pass_test.cc, xls/tests/dslx_optimization_test.cc
The bug occured because we reused BDD analysis generated before OneHot MSB simplification after OneHot MSB simplification. Although the OneHot transform is only performed if the output is unaffected, this transform may change intermediate values. The previous BDD analysis on such intermediate values may therefore no longer be accurate. Fixed by performing a fresh analysis after the OneHot Transfrom.
Fixes #115
=> Fixed bug in BDD simplification pass. 

Dockerfile, README.md
The `python-is-python3` package in Ubuntu 20.04 provides `/usr/bin/python` as a symlink to `python3`, which can be used to simply the setup process.
=> Simplify setup using python-is-python3

dependency_support/com_github_grpc_grpc/BUILD, dependency_support/com_github_grpc_grpc/grpc-cython.patch, dependency_support/initialize_external.bzl, dependency_support/load_external.bzl, dependency_support/pip_requirements.txt
Proposed PR fixes build on more recent systems.
* Increase the default 600s (way too small) timeout for **pip_deps** fetches.
* Impose a newer **cython** compatible with python 3.9 too.
* Update **grpc** to be able build with latest gcc-10.2.1 too.
* Request newer **scipy** buildable with gcc-10.2.1 and python 3.9 headers
These fixes works on a Fedora 34 (rawhide) distro.
Thank You !
----------
PS:
* Preparing more patches towards (optional) distro friendly **unbundled** builds, (like ```systemlibs``` option for tensorflow)
#141
=> Fixes for python3.9 and gcc-10.2.1

README.md
The current version tells the user to install python3-dev twice.
I think the intention is to install both python-dev *and* python3-dev,
but there is a typo here.
=> Fix typo in README.md install instructions

xls/ir/node.h, xls/passes/BUILD, xls/passes/post_dominator_analysis.h, xls/passes/select_simplification_pass.cc, xls/passes/select_simplification_pass_test.cc
Closes #145 
Adds a step to `SimplifyNode` in the select simplification pass that will try to specialize the arms of the select. The current implementation does not support simplifying cases where the selector is not post-dominated by the arm, and works by doing an exact match on the selector within each arm.
Test by running: `bazel test -c opt --test_output=errors //xls/passes/...`
=> Specialize select arms

xls/contrib/integrator/BUILD, xls/contrib/integrator/ir_integrator.cc, xls/contrib/integrator/ir_integrator.h, xls/contrib/integrator/ir_integrator_test.cc, xls/ir/function.cc, xls/ir/function.h, xls/ir/function_base.h, xls/ir/function_test.cc, xls/ir/nodes_source.tmpl, xls/ir/op_specification.py, xls/ir/package.cc, xls/ir/package.h, xls/ir/package_test.cc
...which will be used to combine multiple functions into a single function capable of implmenting all original functions. The initial code copies the source functions into a new package where they can be combined. Functions to be merged should be in the same package to ensure type compatibility. This required extending Function's clone method to enable call site remapping.  This way, we can recursively copy functions and their callees such that the cloned caller function calls the cloned callee function. Additionally, a GetType(Type*) function is added to Package.  This allows us to take a Type from one package and fetch / construct a corresponding Type in another package.
=> Added ir_integrator

xls/visualization/ir_viz/templates/splash.tmpl
Otherwise it can be confusing when nodes are missing in the visualization and the "only view selected" toggle is off (when in actuality the graph is only rendering the selected nodes)
=> Use html checkbox checked state on initial draw

xls/contrib/integrator/ir_integrator.cc, xls/contrib/integrator/ir_integrator.h, xls/contrib/integrator/ir_integrator_test.cc
Added functions to merge two nodes and estimate the cost of merging two nodes. These frontend function call a common backend function. Sharing a common backend will let us implement a given merge optimization (e.g. merge adds of different bitwidths) in a single place, rather than having duplicate logic to estimate the cost of a particular optimization and to actually implement the optimization. To enable merging and cost estimation, added a UnifyNodeOperands function to unify all operands of two nodes and a DeUnifyIntegrationNodes function to undo a previous unification.
=> Functions for merging nodes.

xls/contrib/integrator/ir_integrator.cc, xls/contrib/integrator/ir_integrator.h, xls/contrib/integrator/ir_integrator_test.cc
Added option to configure an entire integrated graph to match one of the source functions using a global select signal.  Useful if we are sure that we only want to execute the source functions on the circuit.  Also helfpul if we wish to merge if/else paths in a single circuit.
Added GetInsertNodeCost function and rewrote InsertNode to call MergeNodesBackend behind the scenes (life will be easier if insert is just a special case of merge instead of being its own operation that we have to think about).
=> Added global mux select signal option.

docs_src/ir_semantics.md
There were a couple of swapped names in the IR semantics docs.
=> [docs] Fix a couple of small typos in IR op descriptions

xls/dslx/ir_converter.cc, xls/dslx/ir_converter_test.cc, xls/dslx/testdata/ir_converter_test_CountedForWithLoopInvariants.ir, xls/dslx/tests/BUILD, xls/dslx/tests/const_value_as_nested_loop_bound.x, xls/dslx/tests/derived_parametric_value_as_nested_loop_bound.x, xls/dslx/tests/parametric_value_as_nested_loop_bound.x
For constants used in a loop body but defined outside the loop, reproduce constant nodes in in the loop body instead of passing these nodes to the loop body function as arguments.  This preserves const-ness. Motivating use case was nested loops where the loop bound was defined by a parametric value. Previously, this would not compile because inner loop bounds would appear as non-const parameters of the outer loop body.
=> Constant loop body paramters converted to loop-internal constants

.github/workflows/one-bazel-test.yml
Adds a manual workflow that can be used for running individual tests, optionally with repetitions via `runs_per_test`, via GitHub actions workflow. This can be useful for understanding why a CI test was failing.
=> Solo bazel test workflow.

xls/common/math_util.h, xls/dslx/stdlib/apfloat.x, xls/dslx/stdlib/bfloat16.x, xls/dslx/stdlib/float32.x, xls/dslx/stdlib/float64.x, xls/modules/BUILD, xls/modules/fp_fast_rsqrt_32.x, xls/modules/fp_fast_rsqrt_32_test.cc, xls/modules/fpsqrt_32.x, xls/modules/fpsqrt_32_test.cc
Square root implementation is based on the go implementation, which is based on a FreeBSD implementation (see file for license / references).
Fast inverse square root is based on a widley publicized algorithm that was popularized by it's use in the game Quake.  However, its actual provenance seems to be pretty fuzzy.  Given that the algorithm is very well-known / widespread, that there is not an obvious license associated with the concept, and that implementing the algorithm in DSLX necessarily results in different code than sources available online, I'm inclined to think we don't have to do anything re licensing here, but I'm no expert.
=> Added floating point square root and fast (approximate) inverse square root.

docs_src/contributing.md, docs_src/dslx_reference.md, docs_src/fpadd_example.md, mkdocs.yml
Introduces three language annotations (all of which map to Rust for
Pygments syntax highlight purposes):
* `dslx`: A full code block that should be parsed/typechecked/tested.
* `dslx-snippet`: A fragment that should be syntax highlighted but not
parsed/typechecked/tested.
* `dslx-bad`: An example of something that we expect to produce an error
when parsing/typechecking/testing.
Adds note on language tags to contributing docs.
Towards google/xls#378
=> Get DSL code to syntax highlight in the mkdocs

xls/public/python/BUILD, xls/public/python/runtime_build_actions.cc, xls/public/python/runtime_build_actions_test.py
This will allow better integration with other python based EDA tools (like `litex`, `migen` and `nmigen`).
/cc @tcal-x who was interesting into discussing ways to ease XLS binary distribution.
=> [public]: add python bindings

third_party/xls_colors/BUILD, third_party/xls_colors/LICENSE, third_party/xls_colors/fast_hsv2rgb.h, third_party/xls_colors/fast_hsv2rgb_32bit.c, third_party/xls_colors/hsv2rgb.x, third_party/xls_colors/test.cc, xls/BUILD
Fast HSV to RGB conversion.
Ported from https://www.vagrearg.org/content/hsvrgb (MIT license).
- Translated https://www.vagrearg.org/hsvrgb/fast_hsv2rgb_32bit.chttps://www.vagrearg.org/hsvrgb/fast_hsv2rgb_32bit.c to unsafe Rust.
- Converted pointers swap to a match expression.
- Converted `mut`s and statements to let expressions.
- Ported to DSLX.
=> [examples] add hsv2rgb

README.md
The bazel invocation listed in the README doesn't seem to work with bazel 4.2.1. This updates the README to work with the current main / bazel release.
=> Update with correct bazel/test invokation

dependency_support/load_external.bzl
The listed commit for the boringssl dependency points to a version that doesn't build with GCC 11.1, which means that XLS doesn't build with GCC 11.1. The underlying issue was fixed in boringssl commit [92c6fbfc4c44dc8462d260d836020d2b793e7804](https://boringssl.googlesource.com/boringssl/+/92c6fbfc4c44dc8462d260d836020d2b793e7804) and is currently in boringssl `main`. This updates the commit to `main-with-bazel` of boringssl as of 2021-11-01 and allows XLS to build with GCC 11.1.
=> Bump up BoringSSL commit

dependency_support/rules_hdl/workspace.bzl
This new release fixes an ncurses mirror issue.
=> [dependency_support] Update to latest rules_hdl repo.

xls/common/subprocess.cc, xls/ir/caret.cc, xls/tools/ice40_device_rpc_strategy.cc
Found while attempting to build on an M1 Mac. Tested in that environment, but not on Linux and/or x86.
I don't love the `#ifdef LINUX`, but I wasn't able to find another way to specialize that the  non-POSIX `c_line` field. I'd be just as happy to drop it. WDYT?
=> Necessary-but-not-sufficient changes to successfully build on OSX.

Dockerfile-ubuntu-22.04
The comment on line 1 of  Dockerfile-ubuntu-22.04 breaks near the end and leaves an un-commented piece on line two. This also needs to be commented out.
=> Need to comment out LTS on line 2

xls/visualization/sched_viz/BUILD, xls/visualization/sched_viz/sched_printer_main.cc
Add a supplementary visualizing tool. It is useful if you want to see the scheduling result on the data dependence graph.
**Features**:
- show critical path explicitly
- nodes and edges on critical path are colored in red
- show pipeline register explicitly
- summary of the total length
- show nodes' name, op(operands...), type, and delay
Here is an example to visualize `crc32.opt.ir`.
```
bazel build //xls/visualization/sched_viz:sched_printer_main //xls/examples:ir_examples
bazel-bin/xls/visualization/sched_viz/sched_printer_main --clock_period_ps=8 --delay_model=unit bazel-bin/xls/examples/crc32.opt.ir > tmp.dot
dot -Tpng tmp.dot -ocrc32.png
```
The output will be:
=> visualize scheduling result: dump to Graphviz's dot file

.github/workflows/nightly-fuzz.yml
The `short_samples` flag was removed w/ https://github.com/google/xls/commit/256461df627dd2650cd96461b4d36b3c4f7854c3.
=> github/workflows: remove obsolete flag from fuzz invocation

.github/workflows/continuous-integration.yml
This makes make the CI outputs actionable.
... this will help to see why the CI tests in #855 fail :)
=> Output errors in tests.

docs_src/scheduling.md
Fixed a broken link and a typo in the scheduling documentation.
=> Scheduling doc typo fix

xls/dslx/ir_convert/extract_conversion_order.cc, xls/dslx/ir_convert/extract_conversion_order.h, xls/dslx/ir_convert/ir_converter.cc, xls/dslx/ir_convert/ir_converter.h, xls/dslx/run_routines.cc, xls/dslx/tests/BUILD, xls/examples/BUILD, xls/flows/ir_wrapper.cc, xls/tools/repl.cc
TestProc and TestFunction were handled differently by GetOrder() function. For TestFunction types calling
```AddToReady``` was an no-op as ```IsReady()``` was
always true.
TestProc handling did not call ```AddToReady``` and
it was adding all proc functions to ready vector.
=> [DSLX/IR] Fix ```assert_eq``` in ```#[test_proc()]```

xls/dslx/frontend/parser_test.cc
`XLS_EXPECT_OK` introduced in f2341af did
cause `TestRoundTripFailsOnSyntaxError` to fail,
although `EXPECT_NONFATAL_FAILURE` was used to catch the `XLS_EXPECT_OK` error.
Issue was that `EXPECT_NONFATAL_FAILURE` expected "ParseError:" in error message, but no error message was given.
I've added `module_or.status()` string conversion as error message.
It was enough to get this test passing.
=> [DSLX] frontend/parser_test.cc: Fix RoundTrip

xls/dslx/frontend/parser_test.cc
This commit adds tests to improve
`zero!<>()` coverage. Some tests are disabled
(GH-#984)
=> [DSLX] Improve zero! coverage.

dependency_support/boost/add_python.patch, dependency_support/boost/workspace.bzl, dependency_support/rules_hdl/workspace.bzl, xls/examples/BUILD
Fixes https://github.com/google/xls/issues/975
This PR:
* bumps boost dependency to v1.82
* uncomments existing place_and_route target under `xls/examples`
* bumps bazel_rules_hdl
In https://github.com/google/xls/commit/f18ad88c7c248e6873fc74c401c8395e03b3296c instead of bumping bazel_rules_hdl I temporarily replaced upstream bazel_rules_hdl with forked repository with branch that includes changes from 3 pending PRs:
* https://github.com/hdl/bazel_rules_hdl/pull/167
* https://github.com/hdl/bazel_rules_hdl/pull/164
* https://github.com/hdl/bazel_rules_hdl/pull/165
Those PRs passed CI tests and are ready for final review. As soon as those will be merged I will remove temporary link to forked bazel_rules_hdl, bump this dependency to the latest version and convert PR from draft to regular …
=> Enable place_and_route targets

xls/common/init_xls.cc
xls/common/init_xls.h specifies that InitXls will call `SetProgramUsageMessage()` to setup `usage` string, but it was never called.
This commit fixes this bug. All XLS binaries will
now display usage message at the beginning of `--help` and `--helpfull`.
=> [XLS] xls/common/init_xls.cc: Fix missing `SetProgramUsageMessage()`

xls/modules/rle/BUILD, xls/modules/rle/rle.x
This PR adds a simple implementation of the RLE Encoder ([Run Length Encoding](https://en.wikipedia.org/wiki/Run-length_encoding)). The introduced changes contain the RLE encoder, tests for the module, rules for Verilog generation, and rules to build IR and Verilog benchmarks.
The changes rely on other features added in separate PRs:
* https://github.com/google/xls/pull/964
* ~~https://github.com/google/xls/pull/973~~
Fixes #994 
CC @proppy
=> Add RLE encoder

xls/dslx/bytecode/bytecode_interpreter.cc, xls/dslx/bytecode/bytecode_interpreter.h, xls/dslx/bytecode/bytecode_interpreter_test.cc
This commit fixes internal error when testing DSLX procs using `#test_proc()`.
Issue was that only first evaluated frame had `type_info` defined, and all following frames had it undefined. This made ConcreteType lookup fail.
Fixes #981
=> [DSLX] Propagating type_info through proc frames

dependency_support/boost/backtrace_from_rule.patch, dependency_support/boost/workspace.bzl
This uses Ethans [libbacktrace support in bazel_rules_hdl](https://github.com/hdl/bazel_rules_hdl/commit/196706dee7fdfeb0ddf916f8a8bd125e0ed0ab45) (that we already depend on).
Without, XLS compilation will fail if the libbacktrace doesn't happen to be part of the local compiler set-up:
```
external/boost/libs/stacktrace/include/boost/stacktrace/detail/libbacktrace_impls.hpp:23:13: fatal error: backtrace.h: No such file or directory
23 | #   include <backtrace.h>
|             ^~~~~~~~~~~~~
compilation terminated.
```
=> Make boost libbacktrace dependency hermetic.

dependency_support/z3/build_defs.bzl, dependency_support/z3/bundled.BUILD.bazel, xls/dslx/ir_convert/function_converter.cc, xls/dslx/ir_convert/function_converter.h, xls/dslx/ir_convert/ir_converter_test.cc, xls/dslx/ir_convert/testdata/ir_converter_test_ArraySizeBuiltin.ir, xls/dslx/type_system/typecheck.cc
Constexpr-evaluates the invocation of the builtin during type inference,
as types are always constexpr so the result is always constexpr.
This is now picked up by IR conversion.
Fixes google/xls#1084
=> [DSLX:ir_convert] Convert `array_size` builtin to IR.

xls/examples/ram.x
Current code does not perform mask width expansion when processing read requests. As a result, configurations with `NUM_PARTITIONS != DATA_WIDTH` fail to compile.
=> bugfix: examples/ram: 1R1W - fix missing mask expansion

xls/common/status/matchers.h, xls/noc/simulation/indexer_test.cc
Fixes https://github.com/google/xls/issues/1112
This PR moves macro `XLS_EXPECT_OK_AND_EQ` which was previously defined in [xls/noc/simulation/indexer_test.cc](https://github.com/antmicro/xls/blob/main/xls/noc/simulation/indexer_test.cc) to [xls/common/status/matchers.h](https://github.com/antmicro/xls/blob/main/xls/common/status/matchers.h) so that it is now widely available.
CC @proppy
=> Move XLS_EXPECT_OK_AND_EQ to matchers

third_party/xls_machsuite/fft/fft.x
Looks like a workaround where a constant value could not be used has been fixed in the meantime, which now can improve the readability of the fft example.
Tested with
bazel test -c opt third_party/xls_machsuite/fft/...
=> Remove workaround not needed anymore in FFT example.

.github/workflows/continuous-integration.yml
as we do not want linux ci jobs to be interrupted by macos failure.
=> github/workflows/ci: fail-fast=false

.bazelrc, dependency_support/com_github_facebook_zstd/BUILD, dependency_support/com_github_facebook_zstd/bundled.BUILD.bazel, dependency_support/load_external.bzl
This PR adds zstd library to the XLS framework. It exposes the following targets:
@com_github_facebok_zstd//:libzstd - zstd library itself
@com_github_facebok_zstd//:zstd - binary for performing zstd compression/decompression
@com_github_facebok_zstd//:decodecorpus - binary for creating test data for a zstd decoder
Additionally, we remove zstd from llvm build to avoid linking conflicts with newly-added zstd library. It seems that llvm_zstd is not necessary for correct llvm operation.
=> modules/zstd: build libzstd

xls/dslx/cpp_transpiler/cpp_type_generator.cc, xls/dslx/cpp_transpiler/test_types_test.cc, xls/dslx/cpp_transpiler/testdata/BasicEnums.cctxt, xls/dslx/cpp_transpiler/testdata/EnumWithConstexprValues.cctxt, xls/dslx/cpp_transpiler/testdata/EnumWithS64.cctxt, xls/dslx/cpp_transpiler/testdata/EnumWithU64.cctxt, xls/dslx/cpp_transpiler/testdata/HandlesAbsolutePaths.cctxt
This pull request adds enum values adjacent to enum names in their string representations.
Fixes issue #1127.
=> Emit actual value along with enum name

dependency_support/initialize_external.bzl, dependency_support/rules_hdl/workspace.bzl
This PR includes fixes for https://github.com/google/xls/pull/1031:
* improve hermetic python handling
* remove cpython and embedded_python_interpreter
Additionally, the bumped version of `bazel_rules_hdl` include work related to improving bazel place_and_route flow (https://github.com/hdl/bazel_rules_hdl/issues/239) and benchmarking experience (https://github.com/google/xls/issues/1226)
CC @proppy
=> dependency_support: bump bazel_rules_hdl

xls/examples/BUILD, xls/modules/rle/BUILD
Closes https://github.com/google/xls/issues/1024
This PR bumps `bazel_rules_hdl` in order to:
* Add `gds_write` rule for writing GDS files (see https://github.com/hdl/bazel_rules_hdl/pull/169).
* Add support for ASAP7 PDK (see https://github.com/hdl/bazel_rules_hdl/pull/176)
Additionally:
* https://github.com/google/xls/pull/1031/commits/65a89c31bf9d1d8adedb325dff9e24c807a5fe36 adds target which builds GDS files for `find_index` example based on the results from previous `place_and_route` targets for ASAP7 and SKY130 technologies.
* https://github.com/google/xls/pull/1031/commits/b67d8b02404d1895789ecf7d1bd378c6135fae95 adds targets for generating GDS files for recently added `RLE` encoder and decoder examples, also for ASAP7 and SKY130.
EDIT:
This PR depends on …
=> Add targets for writing GDS files

mkdocs.yml
replace `polyfill.io` to reduce supply chain risk.
ref: https://blog.cloudflare.com/polyfill-io-now-available-on-cdnjs-reduce-your-supply-chain-risk
polyfillpolyfill/polyfill-service#2834
=> replace `polyfill.io` to reduce supply chain risk

docs_src/dslx_std.md, xls/dslx/stdlib/std.x
This PR adds `round_up_to_nearest_pow2?` functions that can be used rounding up to a multiple
of a known power of 2. The function is a special case of the existing `std::round_up_to_nearest()` function which can be implemented more efficiently when we round up to a power of two.
CC @proppy
=> dslx/stdlib: Add round_up_to_nearest_pow2? functions

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/enhancement-proposal.yml
This updates the XLS issue flow by adding an interstitial step to present users with 3 choices: Bug report, Enhancement proposal, and a link to GitHub discussions.  The Enhancement proposal is a form with specific inputs to aid our triaging process. Previews are below:
**Interstitial "new issue" screen:**
**Bug report:**
**Enhancement proposal form:**
=> Update GitHub issue templates

dependency_support/rules_hdl/workspace.bzl
Bump [bazel_rules_hdl](https://github.com/hdl/bazel_rules_hdl) to a version with fix for segfaults and freezes of openroad (https://github.com/hdl/bazel_rules_hdl/pull/285, openroad fix: https://github.com/The-OpenROAD-Project/OpenSTA/pull/227).
This should fix failures of physical design flows which block https://github.com/google/xls/issues/1211. The example of failing flow is available in [this](https://github.com/google/xls/actions/runs/7990320599/job/21818879438?pr=1213#step:8:24507) CI run.
CC @proppy
=> dependency_support: rules_hdl: bump repository

xls/interpreter/BUILD, xls/interpreter/force_assert.ir, xls/interpreter/serial_proc_runtime.cc, xls/interpreter/serial_proc_runtime_test.cc
Fixes https://github.com/google/xls/issues/1394
This PR adds 2 test cases for the `SerialProcRuntime`. Those test cases launch the simulation of a simple IR design with a proc that contains only the `assert()` operation.
One test case uses `CreateInterpreterSerialProcRuntime()` and the second uses `CreateJitSerialProcRuntime()`. It is expected that Tick'ing the simulation will result in an error due to the `assert()` operation in the simulated IR. The error is handled by the test logic so that the test case succeeds when `Tick()` returns `absl::StatusCode::kAborted` status.
As described in https://github.com/google/xls/issues/1394 initially, only the Interpreter-based simulation was able to catch asserts.
In order to fix this for the JIT runtime, another check of the `assert_msgs` event …
=> Fix assert handling in JitSerialProcRuntime

.github/workflows/continuous-integration.yml, .github/workflows/nightly-fuzz.yml, .github/workflows/nightly-macos.yml
The github action terminal output can't deal with the in-place update of the Compiling status updates and spams endless lines with the regular refresh, hiding actual potential issues in a wall of text.
=> CI: run bazel with --noshow_progress to be less noisy in output.

xls/public/BUILD, xls/public/c_api.cc, xls/public/c_api.h, xls/public/c_api_test.cc
For starters just `xls_convert_dslx_to_ir` APIs are exposed as a sample API towards getting a DSO online (i.e. `libxls.so`).
(My intent is to wrap this DSO in a Rust crate published to crates.io.)
The DSO will be created via a github action -- I'll develop a workflow that publishes a DSO outside the canonical repository and then we can discuss where is best to host/publish the artifact from.
Supercedes https://github.com/google/xls/pull/1390 which I'm intending to close now.
Re: issue tracking, the notion of creating a DSO for easier FFI was mentioned in google/xls#108 but there's no active tracking bug for the Rust crate in google/xls, as I'm not sure what the canonical repo for publishing it will be yet.
=> Start of a C API, amenable to FFI binding [take 2]

xls/examples/BUILD, xls/examples/gcd.x
- stacked on top of #932
- add `gcd_euclidean`
- add `gcd_binary`
- cross-test both implementation using `quicktest`
=> examples: add gcd

xls/dslx/constexpr_evaluator.cc, xls/dslx/frontend/ast.cc, xls/dslx/frontend/ast.h, xls/dslx/frontend/parser_test.cc, xls/dslx/ir_convert/function_converter.cc, xls/dslx/tests/errors/error_modules_test.py, xls/dslx/tests/errors/gh_1473.x, xls/dslx/type_system/parametric_instantiator_internal.cc, xls/dslx/type_system/parametric_instantiator_internal.h, xls/dslx/type_system/typecheck_module_test.cc
Previously we'd get an internal error by running head-first into the bytecode interpreter and it returning us an unbound error from its execution.
This institutes a look-before-you-leap: we look for freevars from the parametric expression that are present in the parametric bindings, and check that those are present in the parametric environment map. If they are not, we provide a more precise and helpful error message.
Ideally we'd be even more aggressive about reporting parametrics that are unbound at the point of instantiation, that is what #1495 is for and why there's a bit of code stubbed out with a TODO in this PR -- there is some investigation needed for the examples that fail with that enabled, but this change strictly moves the ball forward by resolving the issue seen in #1473. …
=> [DSLX:TS] Error on ref to unbound parametrics.

xls/build_rules/xls_macros.bzl
Fixes #1487 
Propagate tags in `xls_dslx_verilog` and `xls_benchmark_ir` bazel macros.
Tags were not propagated correctly which resulted in targets tagged as 'manual' still being executed when running bazel with `//...` or `//:all` patterns
=> Fix tags propagation in bazel macros

xls/public/c_api.cc, xls/public/c_api.h, xls/public/c_api_test.cc
Previously it was accessing a `StatusOr` error variant via `.value()` due to not collapsing the interpreter events correctly.
Also adds value APIs that enable us to invoke "itok" calling convention functions.
=> Add test that `fail!`s and run it via the C API.

xls/dslx/tests/errors/error_modules_test.py, xls/dslx/tests/errors/mod_simple_struct_duplicate.x, xls/dslx/tests/errors/nominal_type_mismatch.x, xls/dslx/type_system/deduce_struct_instance.cc, xls/dslx/type_system/format_type_mismatch.cc, xls/dslx/type_system/maybe_explain_error.cc, xls/dslx/type_system/parametric_instantiator.cc, xls/dslx/type_system/type.cc, xls/dslx/type_system/type.h, xls/dslx/type_system/type_test.cc, xls/dslx/type_system/unwrap_meta_type.cc
Fixes #1500 
* Adds `ToStringInternal(FullyQualify)` on types.
* `ToString` defaults to `FullyQualify::kNo`
* Switch a few spots that were using ostreams from using `ToString()` explicitly to using the `operator<<` which is defined to be `ToString()`
* In the case where we get a type mismatch where the "want" and "got" are identical, instead we do `ToStringFullyQualified()` and use that instead.
=> [DSLX:TS] Fully qualify struct type in error message when strings would otherwise be identical

.gitignore, xls/dslx/fmt/ast_fmt.cc, xls/dslx/fmt/ast_fmt_test.cc, xls/dslx/frontend/ast_cloner.cc, xls/dslx/frontend/parser.cc, xls/dslx/frontend/proc.cc, xls/dslx/frontend/proc.h, xls/dslx/type_system/deduce_utils_test.cc, xls/fuzzer/ast_generator.cc
Fixes #1531 
Leverage the existing `EmitCommentsBetween` helper.
Procs are slightly interesting because we also reorder the proc functions into their canonical order.
As a result, during the pre-pass we emit members with their associated comments, but gather up spans that are relevant to the proc member functions.
Once the pre-pass is complete we can emit the member functions with comments.
Added a "body span" to the `ProcLike` type so we know where the brace open/close are for the `proc` body.
=> autoformat comments on proc members and functions

xls/dslx/frontend/ast.h, xls/dslx/frontend/parser.cc, xls/dslx/frontend/parser.h, xls/dslx/stdlib/std.x, xls/dslx/tests/errors/error_modules_test.py, xls/dslx/tests/errors/imports_and_calls_private_parametric.x, xls/dslx/tests/errors/mod_private_parametric.x, xls/dslx/type_system/deduce_invocation.cc, xls/examples/fp32_fmac.x, xls/examples/lfsr.x, xls/examples/ram.x, xls/examples/sobel_filter.x, xls/modules/zstd/block_dec.x, xls/modules/zstd/ram_printer.x, xls/modules/zstd/repacketizer.x, xls/modules/zstd/sequence_executor.x
Adds an error test and fixes the resulting fallout in examples.
Note that synthetic proc init functions need to inherit their visibility from the proc they are defined inside.
Fixes #1507
=> Respect lack of public annotations for colon-refs

xls/dslx/tests/BUILD, xls/dslx/tests/import_enum_alias.x, xls/dslx/type_system/deduce_utils.cc, xls/dslx/type_system/type_info.cc, xls/dslx/type_system/type_info.h
Fixes google/xls#1540
We were not passing type information for the appropriate module -- a type alias dereferenced a type /in a different module/ so we were obligated to look up the associated type information in the `ImportData`.
Fixes and adds a precondition check to the deduce_utils helper that would have given a closer/more clear proximate cause.
=> Fix type information correlation for transitive enum resolution

xls/modules/zstd/BUILD, xls/modules/zstd/data_generator.cc, xls/modules/zstd/frame_header_test.cc, xls/modules/zstd/zstd_dec_test.cc
Fixes https://github.com/google/xls/issues/1547
CC @proppy
This PR fixes the handling of `absl:Span` with test data input vectors for the `frame_header` tests.
It looks like we must copy the vectors over to the `ZSTDFrameHeader` struct and keep those there for the time of the test case execution and use `absl::Span` based on those copies.
Without this modification we observed that few of the test cases will always fail due to incorrect data under the `input_buffer` span. The interesting thing is that when we commented out all test cases except one of the failing ones (e.g. `FrameHeaderTest.Success`) we noticed that this particular test case started passing indicating that the issue can be triggered by execution of multiple test cases at the same time.
This PR also fixes some formatting …
=> Fix frame header CC tests

dependency_support/load_external.bzl, xls/dslx/frontend/module.cc, xls/dslx/frontend/module.h, xls/dslx/lsp/dslx_ls.cc, xls/dslx/lsp/language_server_adapter.cc, xls/dslx/lsp/language_server_adapter.h, xls/dslx/lsp/language_server_adapter_test.cc, xls/dslx/lsp/lsp_type_utils.cc, xls/dslx/lsp/lsp_type_utils.h, xls/dslx/type_system/deduce.cc, xls/dslx/type_system/type.cc, xls/dslx/type_system/type.h, xls/dslx/type_system/type_test.cc
Was dependent on https://github.com/chipsalliance/verible/pull/2241, which is now submitted.
=> [DSLX:LSP] Add basic support for inlay hints on let bindings.

xls/public/BUILD, xls/public/c_api.cc, xls/public/c_api.h, xls/public/c_api_test.cc
Planned for use in more (Rust-based) OSS tooling (to consolidate on improving one set of verilog generation capabilities).
=> Add start of C API for VAST

xls/dslx/ir_convert/function_converter.cc, xls/dslx/tests/BUILD, xls/dslx/tests/import_u16_type_alias.x, xls/dslx/tests/mod_u16_type_alias.x, xls/dslx/type_system/BUILD, xls/dslx/type_system/deduce.cc, xls/dslx/type_system/scoped_fn_stack_entry.cc, xls/dslx/type_system/scoped_fn_stack_entry.h, xls/dslx/type_system/type_info.cc, xls/dslx/type_system/typecheck_function.cc, xls/dslx/type_system/typecheck_module.cc, xls/dslx/type_system/typecheck_module_test.cc
Towards google/xls#1540 -- in particular fixes the example given in this comment:
https://github.com/google/xls/issues/1540#issuecomment-2297711953
When deducing a ColonRef we get the root type information for the subject, create a new context to deduce the entity being referred to, and we should accordingly push a top level entry onto the function stack for that referred-to module.
Previously we were copying the most recent entry in the function stack, which for a parametric proc indicated we were typechecking within a proc function, which caused the wrong things to happen downstream in the code.
Tightened up some of the invariant checks as well for when we expect there to be a single top-level entry on the function stack.
=> [DSLX:TS] Fix for ColonRef to enum value within proc parametrics.

xls/dslx/tests/errors/error_modules_test.py, xls/dslx/type_system/deduce_expr.cc, xls/dslx/type_system/typecheck_module_test.cc
Fixes https://github.com/google/xls/issues/1587
Trying to interleave ellipsis and empty array handling was prone to bugs, so this splits out DeduceEmptyArray as it's significantly a special path that wants its own path. Seems clearer now.
=> [DSLX:TS] Fix bugs in array-with-ellipsis type inference

xls/dslx/type_system/deduce_expr.cc, xls/dslx/type_system/typecheck_module_test.cc
Fixes #1589 
The fundamental problem is that TypeMismatch errors are semantically
representing "we expected the type to be X but it was Y".
When you try to use that for operands that *are matched, but somehow not
right*, the internal formatting machinery is upset because it's looking
for a discrepancy that should be there as a precondition.
This switches the reporting to be TypeInferenceError, which is the more
correct error in this scenario, and also fixes a likely problem due to
not using `GetBitsLike` adding a test for concatenating with a properly
unsigned `xN`.
=> [DSLX:TS] Fix mismatch errors for concat to be TypeInferenceErrors. 

docs_src/dslx_reference.md, docs_src/floating_point.md, xls/dslx/frontend/ast_utils.cc, xls/dslx/frontend/ast_utils.h, xls/dslx/interp_value.cc, xls/dslx/interp_value.h, xls/dslx/stdlib/apfloat.x, xls/dslx/tests/builtin_type_max.x, xls/dslx/type_system/deduce.cc, xls/dslx/type_system/typecheck_module_test.cc, xls/ir/value.h
In similar fashion to how `ZERO` and `MAX` already existed.
Fixes #1556
=> [DSLX] Add support for `MIN` attribute on builtin bits types.

docs_src/dslx_reference.md, xls/dslx/bytecode/bytecode_emitter.cc, xls/dslx/bytecode/bytecode_emitter_test.cc, xls/dslx/bytecode/bytecode_interpreter.cc, xls/dslx/ir_convert/function_converter.cc, xls/dslx/ir_convert/ir_conversion_utils_test.cc, xls/dslx/stdlib/apfloat.x, xls/dslx/tests/BUILD, xls/dslx/tests/casts_to_xn.x, xls/dslx/type_system/type.cc, xls/dslx/type_system/typecheck_module_test.cc
Fixes #1572 
Development details -- note that `xN` is the first place where the concept of "BitsLike" became load bearing, any place that assumed `ArrayType` in the hierarchy now has to consider that `ArrayType` could be indicating something that's effectively a bits type; i.e. `BitsLike`. Going forward we always want to use `BitsLike` as the test for a type and whether it's effectively a bits type, there were a few spots here that were missed when the `xN` bits type constructor was introduced.
=> [DSLX] Fixes for casting to/from `xN` (bits constructor) based type, adds docs and more tests

xls/dslx/fmt/ast_fmt.cc, xls/dslx/fmt/ast_fmt_test.cc, xls/dslx/fmt/pretty_print.cc, xls/dslx/fmt/pretty_print.h, xls/dslx/frontend/ast.h, xls/dslx/stdlib/apfloat.x, xls/dslx/stdlib/bfloat16.x, xls/dslx/tests/basic_sv_multiline_struct_attr.x, xls/modules/rle/rle_enc_test_utils.x
Fixes #1617
I took assignment on this one because it doesn't fit the normal mold of the autoformatter and pretty printing DSL.
To recap the ideas in the pretty printing DSL (this is a standard technique for pretty printing across programming languages):
- You are always either in flat mode or break mode
- Every entity in the tree has a "flat requirement" -- how many chars it takes up if it's emitted inline
- You can wrap an entity in a "group" to have it reconsider, at that level of the tree, whether its contents can be emitted in flat mode or break mode; i.e. you can request a transition from "multi-line mode" to "single line mode" for any given subtree
The hypothesis of the pretty printing DSL is that /often/ you can write a "heisen-description" where you can describe how an entity is …
=> [DSLX] Allow "leader" of a blocky expression to be inline with a fall-back to nesting the whole construct.

xls/public/BUILD, xls/public/c_api.cc, xls/public/c_api.h, xls/public/c_api_format_preference.h, xls/public/c_api_impl_helpers.cc, xls/public/c_api_impl_helpers.h, xls/public/c_api_vast.cc, xls/public/c_api_vast.h
Since VAST is now in there (as a conceptually "protected" / more prone to change API) with the other public APIs seemed like a good time to break it into some translation units before introducing more "protected" APIs e.g. for DSLX inspection.
=> [c_api] Break C API monolith into multiple sub-targets.

xls/dslx/frontend/ast.h, xls/public/BUILD, xls/public/c_api.h, xls/public/c_api_dslx.cc, xls/public/c_api_dslx.h, xls/public/c_api_test.cc
Draft PR as this is dependent on #1621 landing (after which this will subsequently be rebased).
Note that this uses the multi-translation-unit structured added in the previous PR, adding a new one for DSLX "protected" APIs.
=> [c_api] Add start of C API for DSLX, including inspecting module-scoped type definitions.

xls/dslx/type_system/type.h, xls/public/c_api_dslx.cc, xls/public/c_api_dslx.h, xls/public/c_api_test.cc
Queries whether a type is a bits type with signedness 'true'.
Over time we'll want more detailed helpers for inspecting and interpreting type as its various subtypes, but for purposes of generating some early bridge code this gets us most of what we need.
=> [c_api] Add `xls_dslx_type_is_signed_bits` function.

xls/dslx/fmt/ast_fmt.cc, xls/dslx/fmt/ast_fmt_test.cc
=> [dslx:fmt] Better formatting of a long struct field expression.

xls/dslx/lsp/dslx_ls.cc, xls/dslx/lsp/language_server_adapter.cc, xls/dslx/lsp/language_server_adapter.h, xls/dslx/lsp/language_server_adapter_test.cc
Fixes #1660
Sample view when some logging is added to confirm it's the feature is being triggered appropriately:
=> [dslx:ls] Add support for DocumentHighlight capability.

.github/workflows/modules-zstd.yml, xls/modules/zstd/BUILD, xls/modules/zstd/memory/BUILD, xls/modules/zstd/memory/README.md, xls/modules/zstd/memory/axi.x, xls/modules/zstd/memory/axi_reader.x, xls/modules/zstd/memory/axi_st.x, xls/modules/zstd/memory/axi_stream_add_empty.x, xls/modules/zstd/memory/axi_stream_downscaler.x, xls/modules/zstd/memory/axi_stream_remove_empty.x, xls/modules/zstd/memory/axi_writer.x, xls/modules/zstd/memory/common.x, xls/modules/zstd/memory/mem_reader.x, xls/modules/zstd/memory/mem_writer.x
This PR introduces pros that enable the interface between DSLX modules and AXI subordinates. The attached [README](https://github.com/google/xls/blob/72e55dd291236fa28da3c96d765317e03b9ce6c5/xls/modules/zstd/memory/README.md) provides detailed documentation of the new functionality. Provided Verilog simulations show that the new procs allow for reading from and writing to RAM located on the AXI bus.
While working on this PR, we encountered a potential issue linked to afc720d6a35616c894b6aa342c49554afe0f35cd, which appears to cause indefinite parsing and type-checking loops for certain files, such as `mem_writer.x` (provided in this PR).
=> Add procs for interfacing with AXI peripherals in ZSTD Decoder

xls/dslx/bytecode/bytecode_emitter.cc, xls/dslx/frontend/ast.cc, xls/dslx/frontend/ast.h, xls/dslx/frontend/ast_test.cc, xls/dslx/frontend/ast_utils.cc, xls/dslx/type_system/deduce.cc, xls/dslx/type_system/typecheck_module_test.cc, xls/fuzzer/ast_generator.h, xls/fuzzer/value_generator.cc
Previously we would access `.value()` on an error `StatusOr`
=> [DSLX:type_system] Fix for let binding with `xN` type annotation on it.

xls/dslx/type_system/deduce_expr.cc, xls/dslx/type_system/typecheck_module_test.cc
Previously we would assume we do not need to extend beyond the provided (literal) element count, which led to errors when users did:
```
fn f() -> u32[4] {
let x: u32[4] = [u32:42, ...];  // RHS is actually 1 element here, the u32[4] from the type annotation does /not/ propagate into the array expression as context!
}
```
This also relates to our recent unifying type inference discussions -- in unifying TI we'd make the right hand side type "at least a u32[1] if not more" and then it would unify with `u32[4]` to say "ok it's a u32[4] filled with the value 42". cc @richmckeever @meheff
=> [DSLX:TS] Give an error if there is an ellipsis without a type annotation.

xls/codegen/vast/vast.cc, xls/codegen/vast/vast.h, xls/codegen/vast/vast_test.cc
Adds an `ExternPackageType` to refer to types defined in other packages (that we do not know the underlying bit width for or have a definition to refer to in the current `VerilogFile`).
In the process found it was hard to reason about the invariants of `Emit()` giving back associated spaces for types and `EmitWithIdentifier()` and similar -- reworked that so all Emit functionality gives back a value with no whitespace to strip so the caller knows what to expect. Previously it was confusing/confused because DataKind could be empty string and DataType could also be empty string in various cases. Case in point this fixed an error in the test where there were two spaces after the `output` keyword.
Also adds a bunch of tests for constructs we're about to use in stitching just to ensure they …
=> [VAST] `ExternPackageType` & tighten space invariants.

xls/dslx/bytecode/BUILD, xls/dslx/bytecode/bytecode_emitter.cc, xls/dslx/bytecode/bytecode_interpreter.cc, xls/dslx/dslx_builtins_signatures.cc, xls/dslx/interp_value_utils.cc, xls/dslx/ir_convert/function_converter.cc, xls/dslx/tests/BUILD, xls/dslx/tests/xn_signedness_properties.x, xls/dslx/translators/dslx_to_verilog.cc, xls/dslx/type_system/deduce.cc, xls/dslx/type_system/deduce_enum_def.cc, xls/dslx/type_system/deduce_expr.cc, xls/dslx/type_system/parametric_bind.cc, xls/dslx/type_system/parametric_bind_test.cc, xls/dslx/type_system/type.h, xls/dslx/type_system/type_test.cc, xls/dslx/type_system/type_zero_value.cc, xls/dslx/type_system/typecheck_module_test.cc
`xN` was primarily created so we could write polymorphic metaprogramming on
sign like `sizeof` in the standard library. Since `xN` is not fuzzed beyond
that simple use there were opportunities for mishandling it in IR conversion,
and the DSLX language tests I believe don't run `--compare=jit` anymore. We
should figure out how to fix that and add `xN` to the fuzzer, even though it's
a fairly new feature it is now documented, see https://github.com/google/xls/issues/1572.
I noticed that quickchecks on a function with `xN` was giving odd results,
which was because quickchecks *only* work in the JIT, via IR conversion.
Debugged the discrepancy to `dynamic_cast<BitsType*>` and so knocked out nearly
all of the `dynamic_cast<BitsType*>` and `dynamic_cast<const BitsType*>` in the
code base.  We …
=> [DSLX] Fix handling of `xN`, e.g. in IR converter.

.github/workflows/continuous-integration.yml, xls/codegen/module_builder.cc, xls/codegen/module_builder.h, xls/codegen/module_builder_test.cc, xls/codegen/testdata/combinational_generator_test_ArrayUpdateLiteralIndex.vtxt, xls/codegen/testdata/combinational_generator_test_ArrayUpdateVariableIndex.vtxt, xls/codegen/testdata/combinational_generator_test_ArrayUpdateWithNarrowIndex.vtxt, xls/codegen/testdata/module_builder_test_ArrayUpdate1D.vtxt, xls/codegen/vast/vast.cc, xls/codegen/vast/vast.h, xls/codegen/vast/vast_test.cc
Previously we would create a lot of Verilog output spew (even for simple cases), which can choke downstream tools that are not accustomed to generated files.
This PR sets its sights a bit low and only handles a simple case (1D array of bits typed objects) to keep things a bit more manageable for review. We can extend this technique to nested generate loops in the future from this basis.
VAST note: generate loops are interesting in that they are not statement blocks in a sense, they are “AST construct yielding”, i.e. they yield AST constructs at elaboration time that are appropriate for the enclosing scope. Which is to say, it could be creating ModuleMembers even though the generate loop’s body block is seemingly “within” the direct module scope. As a result, we have the body for a …
=> [codegen] Support genvars & generate loop, use in simple array updates.

xls/dslx/fmt/ast_fmt.cc, xls/dslx/fmt/ast_fmt.h, xls/dslx/frontend/ast.cc, xls/dslx/frontend/ast.h, xls/dslx/frontend/ast_cloner.cc, xls/dslx/frontend/ast_node.h, xls/dslx/frontend/module.cc, xls/dslx/frontend/module.h, xls/dslx/frontend/parser.cc, xls/dslx/frontend/parser.h, xls/dslx/frontend/parser_test.cc, xls/dslx/frontend/scanner_keywords.inc, xls/dslx/ir_convert/extract_conversion_order.cc, xls/dslx/ir_convert/function_converter.cc, xls/dslx/lsp/document_symbols.cc, xls/dslx/lsp/find_definition.cc, xls/dslx/stdlib/tests/float32_test.cc, xls/dslx/type_system/deduce.cc, xls/dslx/type_system/type_info.proto, xls/dslx/type_system/type_info_to_proto.cc, xls/dslx/type_system/typecheck_module.cc
- Adds parsing support for `use` tree and makes `use` a keyword.
- One-line-only formatting support as a stub for the time being.
- Type inference support returns unimplemented for the moment.
Note that `use` introduces the first AST node at module scope that defines multiple NameDefs simultaneously, so small amount of rework in this PR to handle that new development.
Clang was also complaining about the lossy conversion of int32 limits to floats so I fixed that here too.
No documentation yet as it's a WIP construct.
=> [DSLX:FE] Progress on `use` construct #352

xls/contrib/mlir/IR/xls_ops.td
Updates the `xls.yield` documentation in the MLIR dialect, noting that it is also used to terminate procs, not just for-loops.
=> [xls][mlir] Update YieldOp description

xls/fuzzer/BUILD, xls/fuzzer/value_generator.cc, xls/fuzzer/value_generator_test.cc
Per @mikex-oss' stack trace and scenario described in #1774, this function is only called to create a value in proc init generation.
=> [fuzz] Fix up routine only used in proc init function generation.

.bazelrc, xls/dslx/frontend/ast.cc, xls/dslx/frontend/ast.h, xls/dslx/frontend/ast_cloner.cc, xls/dslx/frontend/ast_cloner_test.cc, xls/dslx/frontend/ast_node.h, xls/dslx/frontend/parser.cc, xls/dslx/frontend/parser.h, xls/dslx/ir_convert/function_converter.cc, xls/dslx/type_system/deduce.cc, xls/dslx/type_system/type_info.proto, xls/dslx/type_system/type_info_to_proto.cc
Switch to AstNode for UseTreeEntry is per discussion with @richmckeever -- the rationale is, though we don't quite have it at the moment, in the future we may want to make an arbitrary matcher or replacer that was polymorphic on AstNode types, which makes it useful here to opt to reflect more structure of the AST in the node class form.
=> [DSLX] Switch UseTreeEntry to an AstNode, make a cloner implementation.

docs_src/tutorials/hello_xls.md
Small addition to the "Hello XLS" tutorial: The `trace!` output is not visible by default, and requires `--alsologtostderr` to be seen.
=> [docs] Fix missing interpreter_main flags in hello xls tutorial.

xls/contrib/mlir/testdata/ops_translate.mlir, xls/contrib/mlir/tools/xls_translate/xls_translate.cc
Fixes a small typo in the generation of XLS IR `Next` node in the `xls_translate` tool, which previously assigned the wrong `value`.
Also enables and fixes FileCheck in the `ops_translate.mlir` test, and adds a second `(predicate, next_value)` pair to the `xls.next_value` op. This makes it a valid `xls.next_value` op  (one and only one predicate is true) and triggers the bug.
=> [xls][mlir] Fix XLS IR `Next` node generation in MLIR translation.

xls/dslx/type_system/BUILD, xls/dslx/type_system/typecheck_main.cc
This is the most easily fuzzed binary as it doesn't depend on JIT components. Adding a flag to let it turn internal errors into fatals avoids the need to make a wrapper layer or a custom fuzz target to identify places where we (undesirably) flag internal errors.
=> [DSLX:TS] Add flag to fatal on internal error for typecheck_main.

xls/dslx/type_system/deduce.cc, xls/dslx/type_system/proc_typecheck_test.cc
Previously this caused:
```
C++ exception with description "Bad StatusOr access: INVALID_ARGUMENT: Type "token" has no defined signedness." thrown in the test body.
[  FAILED  ] TypecheckErrorTest.TokenHasNoSignedness (3 ms)
```
=> [DSLX:TS] Fix array type annotation that would create internal error.

xls/dslx/bytecode/bytecode_emitter.cc, xls/dslx/bytecode/bytecode_emitter.h, xls/dslx/bytecode/bytecode_emitter_test.cc, xls/dslx/constexpr_evaluator.cc, xls/dslx/constexpr_evaluator.h, xls/dslx/frontend/ast.cc, xls/dslx/frontend/ast.h, xls/dslx/frontend/ast_cloner.cc, xls/dslx/frontend/ast_cloner_test.cc, xls/dslx/frontend/ast_node.h, xls/dslx/frontend/parser.cc, xls/dslx/frontend/parser.h, xls/dslx/frontend/parser_test.cc, xls/dslx/ir_convert/extract_conversion_order.cc, xls/dslx/ir_convert/function_converter.cc, xls/dslx/ir_convert/function_converter.h, xls/dslx/type_system/deduce.cc, xls/dslx/type_system/parametric_instantiator_internal.cc, xls/dslx/type_system/type_info_to_proto.cc, xls/dslx/type_system_v2/typecheck_module_v2.cc, xls/fuzzer/ast_generator.cc, xls/fuzzer/ast_generator.h
Similar to https://github.com/google/xls/pull/1753 this node is trying to reflect type-check-time information in the AST. It is better to remove the parse-time indicator and derive the information consistently in type checking.
=> [DSLX:FE:cleanup] Remove ConstRef node.

xls/codegen/block_generator_test.cc, xls/contrib/ice40/ice40_device_rpc_strategy.cc, xls/data_structures/inline_bitmap.h, xls/ir/BUILD, xls/ir/bit_push_buffer.cc, xls/ir/bit_push_buffer.h, xls/ir/bit_push_buffer_test.cc, xls/ir/bits.cc, xls/ir/bits.h, xls/ir/bits_test.cc, xls/public/c_api.cc, xls/public/c_api.h, xls/public/c_api_symbols.txt, xls/public/c_api_test.cc
Functionality for helping serialize XLS values to bit strings and C API functions for working with bits values.
Adds some functionality to BitPushBuffer so that we can piggyback on the existing Value::FlattenTo facilities.
Previously it would only allow padding in the least significant bits to get byte aligned results, but this adds a routine that can place the padding into the most significant bits of the first byte.
=> [c_api] C APIs for dealing with bits values and flattening aggregates to bits.

xls/dslx/fmt/ast_fmt.cc, xls/dslx/frontend/ast_cloner_test.cc, xls/dslx/frontend/module.cc, xls/dslx/frontend/module.h, xls/dslx/frontend/parser.cc, xls/dslx/frontend/parser_test.cc
Feature flag to gate the `use` syntax until support is more complete.
There are some distributed challenges in enabling it comprehensively because, e.g. for IR conversion, before we could assume that all "external references" were via a ColonRef AST construct, but now they are NameDefs in the local module scope that happen to have their definition externally.
Towards #352
=> [DSLX:FE] Add feature flag to gate `use` syntax.

xls/dslx/type_system/deduce_expr.cc, xls/dslx/type_system/type.cc, xls/dslx/type_system/type.h, xls/dslx/type_system/typecheck_module_test.cc
Previously this would cause a crash.
=> [DSLX:TS] Don't crash on "member[0] of array is a type ref" scenario.

xls/dslx/bytecode/bytecode.h, xls/dslx/bytecode/bytecode_emitter.cc, xls/dslx/bytecode/bytecode_emitter.h, xls/dslx/bytecode/bytecode_interpreter.cc, xls/dslx/bytecode/bytecode_interpreter_test.cc, xls/dslx/interp_value.cc
We already note in the type information what we deduced for the slice start/size as they must be constexpr. This change prevents duplication of logic which can be subtly off/different by keying off the type information data as much as possible.
Fixes google/xls#1784
=> [DSLX:BC] Remove logic from bytecode emitter, consolidate on type information

xls/dslx/bytecode/bytecode.cc, xls/dslx/bytecode/bytecode.h, xls/dslx/bytecode/bytecode_emitter.cc, xls/dslx/bytecode/bytecode_interpreter.cc, xls/dslx/bytecode/bytecode_interpreter.h, xls/dslx/bytecode/bytecode_interpreter_test.cc, xls/dslx/bytecode/interpreter_stack.h
Previously the bytecode interpreter thought it returned like `trace_fmt!` does, but historically `trace!` acted as an identity function so you could easily wrap it around any given subexpression, like:
```
let binding = f(a * b + c);
```
instrumenting the interior subexpression like so:
```
let binding = f(trace!(a*b)+c);
```
The fact they disagreed led to typecheck flagging a program through but then getting a bytecode interpreter error in the bowels of InterpValue.
Note that `trace_fmt!` and `trace!` are different in that the latter requires and operand but the former can just take a format string and zero operand args, so they are implemented as two bytecode ops that call into common functionality.
=> [DSLX:BC] Fix disagreement between typechecker and interpreter on whether `trace` returns its operand

.bazelrc, docs_src/dslx_reference.md, xls/data_structures/inline_bitmap.h, xls/dslx/fmt/ast_fmt.cc, xls/dslx/frontend/ast.cc, xls/dslx/frontend/ast.h, xls/dslx/frontend/ast_cloner.cc, xls/dslx/frontend/parser.cc, xls/dslx/frontend/parser.h, xls/dslx/run_routines/run_comparator.h, xls/dslx/run_routines/run_routines.cc, xls/dslx/run_routines/run_routines.h, xls/dslx/run_routines/run_routines_test.cc, xls/dslx/tests/errors/error_modules_test.py, xls/ir/bits.h, xls/ir/value.cc, xls/ir/value.h, xls/ir/value_test.cc
Fixes #1715 
- Add support for exhaustive directive on quickchecks, updates docs.
- Adds a bitmap view, which is helpful for looking at substrings of an overall bit vector when we're trying to populate aggregate values from an underlying bit string.
- Plumbs a filesystem factory into the run routines for purposes of testing.
- Adds `Value::PopulateFrom(BitmapView)` and does round trip fuzz testing on it
- Adds a warning-as-error to the OSS .bazelrc, previously you could forget to return values in a function with a stated return type without getting an error
=> [DSLX:run_routines] Enable quickcheck to be exhaustive.

xls/ir/function_builder.cc
Fixes an incorrect error message in the "decode" function builder.
=> [XLS] Fix incorrect error message.

docs_src/dslx_ffi.md, docs_src/dslx_reference.md, docs_src/dslx_std.md, docs_src/dslx_type_system.md, docs_src/tutorials/float_to_int.md, docs_src/tutorials/hello_xls.md, docs_src/tutorials/how_to_use_procs.md, docs_src/tutorials/intro_to_parametrics.md, docs_src/tutorials/what_is_a_proc.md, xls/dslx/dslx_fmt.cc, xls/dslx/fmt/ast_fmt_test.cc, xls/tests/BUILD, xls/tests/documentation_test.py
Trying to make an issue like #1831 not possible going forward via testing.
However, I was also not able to reproduce the issue reported in #1831, even with the directed tests in here cc @mikex-oss it's possible your `dslx_fmt` tool in that report was stale?
=> [DSLX] Auto-format documentation examples, enforce in `documentation_test.py`

xls/contrib/mlir/tools/xls_translate/xls_translate.cc
@jpienaar 
Fixes a small copy-paste error: Error messages for "BlockingReceiveOp" and "NonblockingReceiveOp" erroneously reference "SendOp"
=> [xls][mlir] Fix incorrect error messages.

xls/dslx/type_system/deduce.cc, xls/dslx/type_system/typecheck_module_test.cc
=> [DSLX:TS] Cannot index a parameteric-signedness value.

xls/contrib/mlir/IR/xls_ops.td, xls/contrib/mlir/testdata/ops_translate.mlir
This mirrors XLS IR's behavior: Equality comparisons are permissible between two operands of arbitrary but equal types.
=> [xls][mlir] Allow non-bits operands for EqOp and NeOp

xls/contrib/mlir/IR/xls_ops.td, xls/contrib/mlir/testdata/ops_translate.mlir
Mirrors XLS IR behavior. XLS Arrays can contain non-bits values, and the update op needs to support that.
=> [xls][mlir] Allow non-bits values as array update operand

xls/dslx/frontend/parser.cc, xls/dslx/frontend/parser_test.cc, xls/dslx/tests/errors/error_modules_test.py, xls/dslx/tests/errors/unsized_array_type.x
Helps to guide if folks assume they can make an array with no constant size as a way of representing an arbitrary-sized slice.
=> [DSLX:FE] Better error message if you try to use "unsized" array types.

xls/contrib/mlir/IR/xls_ops.td, xls/contrib/mlir/testdata/ops_translate.mlir
While rare (next_value nodes are introduced during optimization, which typically flattens the state to only `bits`-typed values), XLS IR does support more complex state member types. This patch allows this also in the MLIR dialect.
=> [xls][mlir] Allow non-bits typed next_value operands.

.github/workflows/continuous-integration.yml, Dockerfile-ubuntu-22.04
Primarily adds "zip" to the installation -- we were relying on this somehow as a system dependency for our xls/fuzzer test targets, I didn't dig into exactly how.
Add common flags and wildcards I use when doing project wide testing.
Fixes #1862
=> Fix fuzz tests relying on zip binary in docker image build.

xls/dslx/bytecode/bytecode_cache.cc, xls/dslx/bytecode/bytecode_cache.h, xls/dslx/bytecode/bytecode_cache_interface.h, xls/dslx/bytecode/bytecode_interpreter.cc, xls/dslx/create_import_data.cc, xls/dslx/run_routines/run_routines.cc
Previously the BytecodeCache would take a pointer to the ImportData but then we would move it out of the factory function. This erroneously assumes the pointer cannot be moved when it is being returned by value.
This PR solves for this by just passing in the import data from the outside world, which is not difficult in our code base.
=> [DSLX] Get rid of unsound pointer stability assumption.

.github/workflows/continuous-integration.yml, xls/dslx/type_system/deduce.cc, xls/dslx/type_system/deduce.h, xls/dslx/type_system/deduce_ctx.cc, xls/dslx/type_system/type.cc, xls/dslx/type_system/type.h, xls/dslx/type_system/type_test.cc, xls/dslx/type_system/typecheck_module_test.cc
There were incompatibilities reported confusingly because the bit widths of the signedness were different; e.g. `u1:0` vs `u32:0` (note the difference in type bitwidth) where we don't visually show the width of the signedness when we print in `xN[is_signed=0][8]` sort of form.
Note: not sure why but I'm seeing package installation issues with the CI action, e.g. https://github.com/google/xls/actions/runs/12818961097/job/35745586502 around python3-distutils and libtinfo5.
Fixes #1861
=> [DSLX:TS] Fix issues with type compatibility for parametric signedness params

.pre-commit-config.yaml, xls/dslx/interp_value.cc, xls/dslx/type_system/deduce.cc, xls/dslx/type_system/deduce_utils.cc, xls/dslx/type_system/deduce_utils.h, xls/dslx/type_system_v2/inference_table_to_type_info.cc, xls/dslx/type_system_v2/solve_for_parametrics.cc, xls/dslx/type_system_v2/type_annotation_utils.cc, xls/dslx/type_system_v2/type_annotation_utils.h, xls/dslx/type_system_v2/typecheck_module_v2.cc, xls/dslx/type_system_v2/typecheck_module_v2_test.cc
The type annotation the user provides is the type annotation that results from the cast expression.
It is validated when we go to finalize the inference table into type information, where we have concrete types that can check whether it is an acceptable cast.
Note that I also switched from S64 to U32s for default "usize like" usage and put a link to the relevant github issue where it explains why it'd be nice to have a usize type for this purpose similar to Rust.
=> [DSLX:TIv2] Implement cast operation.

xls/dslx/bytecode/bytecode_emitter.cc, xls/dslx/constexpr_evaluator.cc, xls/dslx/tests/BUILD, xls/dslx/tests/attr_via_local_type_alias.x, xls/dslx/tests/attr_via_local_type_alias_in_parametric.x, xls/dslx/type_system/deduce_utils.cc, xls/dslx/type_system/deduce_utils.h, xls/dslx/type_system/typecheck_module_test.cc
Previously these samples would cause RET_CHECKs because the constexpr evaluator and bytecode emitter would try to resolve constexprs that weren't present.
Note: the duplicated structure between the constexpr evaluator and bytecode emitter does suggest we probably want an "abstract evaluator" scaffolding of sorts to factor out the commonalities.
=> [DSLX] Fix type info switching being wrong for local type aliases.

.pre-commit-config.yaml, xls/codegen/vast/dslx_builder.cc, xls/dslx/cpp_transpiler/cpp_type_generator.cc, xls/dslx/fmt/ast_fmt.cc, xls/dslx/frontend/ast.cc, xls/dslx/frontend/ast.h, xls/dslx/frontend/ast_utils.cc, xls/dslx/frontend/bindings.cc, xls/dslx/frontend/bindings.h, xls/dslx/frontend/module.cc, xls/dslx/frontend/module.h, xls/dslx/frontend/parser.cc, xls/dslx/tests/BUILD, xls/dslx/tests/mod_imported_parameterized_type_alias.x, xls/dslx/tests/mod_use_parameterized_type_alias.x, xls/dslx/translators/dslx_to_verilog.cc, xls/dslx/type_system/deduce.cc, xls/dslx/type_system/deduce_utils.cc, xls/dslx/type_system/type_info.cc, xls/dslx/type_system/type_info.h, xls/dslx/type_system_v2/type_annotation_utils.cc, xls/fuzzer/value_generator.cc, xls/public/c_api_dslx.cc, xls/public/c_api_dslx.h
Fix for the scenario where we use a type definition into the module scope and then instantiate it in a type alias. Add a `dslx_lang_test` for this.
Note that this adds `UseTreeEntry` as a node that can be a `TypeDefinition`.
Progress towards #352
=> [DSLX] Fix `use` of a type instantiated in a alias.

xls/dslx/dslx_fmt.cc, xls/dslx/dslx_fmt_test.py
This lets us slot into a pre-commit hook more easily, looks like it batches up about 8 files at a time by default to avoid too many subprocess invocations.
=> [dslx_fmt] Support multiple arguments as input, similar to other formatters

xls/dslx/frontend/parser.cc, xls/dslx/frontend/parser_test.cc, xls/dslx/frontend/scanner_keywords.inc
It's common for new users and/or people coming from Rust knowledge to try typing `let mut` -- this gives a better error message when they try to do that, and reserves `mut` as a keyword for any potential of future usage (though that is not planned).
=> [DSLX:FE] Better error on `mut` usage, reserve `mut` as a keyword.

xls/dslx/run_routines/run_routines.h, xls/dslx/run_routines/run_routines_test.cc
per cpp style (lowercase should be simple accessors that do no work)
=> [DSLX:RR][cleanup] Rename failures to GetFailureMessages

xls/dslx/ir_convert/function_converter.cc, xls/dslx/ir_convert/function_converter.h, xls/dslx/ir_convert/ir_converter_test.cc, xls/dslx/ir_convert/testdata/ir_converter_test_ForOverArrayLiteral.ir, xls/dslx/ir_convert/testdata/ir_converter_test_ForOverArrayOfItems.ir, xls/dslx/tests/BUILD, xls/dslx/tests/enumerate.x, xls/dslx/tests/for_over_array.x, xls/dslx/tests/for_over_range.x, xls/dslx/tests/for_over_range_u8.x, xls/ir/function_builder.cc
This also factors the for-loop handling into a few more decomposed functions so the new functionality didn't grow the large method even larger.
Makes some of the language tests have main() functions so we can observe whether IR conversion was successful.
=> [DSLX:ir_conv] IR convert for-loop over array items.

xls/dslx/bytecode/bytecode_emitter_test.cc, xls/dslx/frontend/ast.h, xls/dslx/type_system/deduce.cc, xls/dslx/type_system/typecheck_module_test.cc
This helps completeness of constexpr assessment for exhaustiveness in match pattern expressions.
=> [DSLX:TS] Mark const NameRefs as constexprs (also in match patterns).

xls/dslx/frontend/parser.cc, xls/dslx/frontend/parser.h, xls/dslx/frontend/parser_test.cc, xls/dslx/ir_convert/ir_converter_test.cc
Came across that this was acting like another kind of wildcard when rebasing the exhaustiveness-checking change.
Per https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=67b999ff70ddc15c57a9c2c3437616e1 the .. can only appear within a tuple pattern (we don't support the other forms Rust mentions there yet).
=> [DSLX:FE] Rest-of-tuple pattern can only appear within a tuple (match Rust)

xls/contrib/mlir/IR/xls_ops.td, xls/contrib/mlir/testdata/ops_translate.mlir, xls/contrib/mlir/tools/xls_translate/xls_translate.cc
@jpienaar 
Adds the following XLS-supported ops to the MLIR dialect:
- nand, nor
- and_reduce, or_reduce, xor_reduce
- umulp, smulp
- gate
Note that for the partial product operations, operands of different bit widths and operands of different bit width than the result are explicitly allowed.
Please double check the following in the tablegen ODS for partial product ops:
```tablegen
TypesMatchWith<"result types must match", "result_lhs", "result_rhs", "$_self">
```
Is this a sane way of constraining the two result values to have the same type? Is there a different constraint that matches better? Seems like a bit of a hack to use this with the "identity transform expression" "$_self" :)
=> [xls][mlir] Add missing MLIR dialect ops

xls/contrib/mlir/IR/interfaces.td, xls/contrib/mlir/IR/xls_ops.cc, xls/contrib/mlir/IR/xls_ops.td, xls/contrib/mlir/testdata/ops.mlir
This operation constructs a literal of arbitrarily complex type using a body region that construct this value using basic scalar operations.
It more closely resembles the XLS literal IR node for loss-less conversion between the IR and MLIR, but is not intended to be used during complex operations and transforms in MLIR due to the lack of constant folding.
A pass to remove this operation by inlining (and potentially a pass to reconstruct such literal ops by grouping ops) will be added in the future.
Only a small subset of XLS operations is permitted inside the body region. The new LiteralMemberOpInterface is used to identify such ops.
=> [xls][mlir] Add LiteralOp to XLS MLIR Dialect.

xls/contrib/mlir/BUILD, xls/contrib/mlir/IR/xls_ops.td, xls/contrib/mlir/testdata/BUILD.bazel, xls/contrib/mlir/testdata/lit.cfg.py, xls/contrib/mlir/testdata/ops.mlir, xls/contrib/mlir/testdata/ops_translate.mlir, xls/contrib/mlir/testdata/translate_from_xls/arithop.ir, xls/contrib/mlir/testdata/translate_from_xls/array.ir, xls/contrib/mlir/testdata/translate_from_xls/binop.ir, xls/contrib/mlir/testdata/translate_from_xls/bitslice.ir, xls/contrib/mlir/testdata/translate_from_xls/compareop.ir, xls/contrib/mlir/testdata/translate_from_xls/extendop.ir, xls/contrib/mlir/testdata/translate_from_xls/invoke.ir, xls/contrib/mlir/testdata/translate_from_xls/literal.ir, xls/contrib/mlir/testdata/translate_from_xls/naryop.ir, xls/contrib/mlir/testdata/translate_from_xls/onehot.ir, xls/contrib/mlir/testdata/translate_from_xls/proc.ir, xls/contrib/mlir/testdata/translate_from_xls/sel.ir, xls/contrib/mlir/testdata/translate_from_xls/tuple.ir, xls/contrib/mlir/testdata/translate_from_xls/unop.ir, xls/contrib/mlir/tools/xls_translate/xls_translate.cc, xls/contrib/mlir/tools/xls_translate/xls_translate_from_mlir.cc, xls/contrib/mlir/tools/xls_translate/xls_translate_from_mlir.h, xls/contrib/mlir/tools/xls_translate/xls_translate_main.cc, xls/contrib/mlir/tools/xls_translate/xls_translate_to_mlir.cc, xls/contrib/mlir/tools/xls_translate/xls_translate_to_mlir.h
As requested, here is a combined PR that implements the XLS IR -> MLIR translation.
A few notes up front about the state of this:
- This relies on two PRs that are not yet merged - I have kept them in this PR branch so it is functional and will drop them + rebase once #1866 and #1843 are in.
- This currently implements full-fidelity round trip conversion for XLS functions. 
- Procs are mostly supported with the main limitation that non-zero initializers are not yet representable. This is WIP because it requires reworking of the yield OPs which is fairly invasive and I did not want commit to it until the "LiteralRegion" mechanism had been reviewed + merged.
- The notion of "top proc/func" is not yet translated/represented in MLIR.
- I have setup fuzzing of XLS->MLIR->XLS conversion that …
=> [MLIR] XLS -> MLIR Translation

xls/dslx/diagnostics/BUILD, xls/dslx/diagnostics/warn_on_defined_but_unused.cc, xls/dslx/diagnostics/warn_on_defined_but_unused.h, xls/dslx/diagnostics/warn_on_defined_but_unused_test.cc, xls/dslx/frontend/ast_utils_test.cc, xls/dslx/frontend/parser.cc, xls/dslx/type_system/typecheck_function.cc
- Makes WarnOnDefinedButUnused take a TypeInfo and a WarningCollector instead of a DeduceCtx to make it more capable of being unit tested
- Write a few unit tests for scenarios of interest
Towards #1909
=> [DSLX:TS] Unit tests for defined-but-unused scenarios.

MODULE.bazel, dependency_support/load_external.bzl
https://github.com/bazelbuild/bazel-central-registry/pull/3691 landed, which provides a new-enough version that we can use directly.
=> Use cppitertools in MODULE.bazel

.gitignore
The new compilation DB extraction setup produces a `compile_flags.txt` instead of a `compile_commands.json` file.
=> Add `compile_flags.txt` to .gitignore

xls/contrib/mlir/tools/xls_translate/xls_translate_from_mlir.cc, xls/dslx/ir_convert/convert_options.h, xls/dslx/ir_convert/ir_converter.cc, xls/dslx/ir_convert/ir_converter_main.cc, xls/dslx/run_routines/ir_test_runner.cc, xls/dslx/warning_collector.h, xls/public/c_api.cc, xls/public/c_api.h, xls/public/c_api_dslx.cc, xls/public/c_api_impl_helpers.cc, xls/public/c_api_impl_helpers.h, xls/public/c_api_symbols.txt, xls/public/c_api_test.cc, xls/public/runtime_build_actions.cc, xls/public/runtime_build_actions.h
Keeps the prior C APIs but adds the versions that take warning parameters as well.
Note that the /public C++ API/ is changed so that we can consolidate a bit vs having APIs with tons of parameters on that side of the equation -- we're not going for a flat "C ABI style" design there. This will require a global check on import.
Adds:
- `xls_convert_dslx_path_to_ir_with_warnings` to supplement `xls_convert_dslx_path_to_ir`
- `xls_convert_dslx_to_ir_with_warnings` to supplement `xls_convert_dslx_to_ir`
- `xls_c_strs_free` to free the dynamically sized warnings array that can be returned from the API
=> [c_api] Public API for DSLX to IR w/ warning knobs.

xls/dslx/tests/BUILD, xls/dslx/tests/std_find_index_on_enum_array.x
Demonstrates how we can use `std::find_index` if we map over the enum array to convert into the underlying type first, since we can't currently (with TIv1) write a stdlib routine that's parameterized over both enum types and bit values.
=> [DSLX:tests] Add sample showing std::find_index on enum array.

xls/dslx/frontend/ast.cc, xls/dslx/frontend/ast.h, xls/dslx/frontend/parser.cc, xls/dslx/frontend/parser_test.cc, xls/dslx/ir_convert/extract_conversion_order.cc, xls/dslx/ir_convert/function_converter.cc, xls/dslx/ir_convert/ir_conversion_utils.cc, xls/dslx/make_value_format_descriptor.cc, xls/dslx/tests/BUILD, xls/dslx/tests/mod_use_simple_enum.x, xls/dslx/tests/mod_use_stdlib.x, xls/dslx/type_system/BUILD, xls/dslx/type_system/deduce.cc, xls/dslx/type_system/deduce_invocation.cc, xls/dslx/type_system/deduce_spawn.cc, xls/dslx/type_system/deduce_utils.cc, xls/dslx/type_system/type.cc, xls/dslx/type_system/type.h, xls/dslx/type_system/type_info.cc, xls/dslx/type_system/type_info.h, xls/dslx/type_system/type_info.proto, xls/dslx/type_system/type_info_to_proto.cc, xls/dslx/type_system/type_zero_value.cc, xls/dslx/type_system/typecheck_invocation.cc, xls/dslx/type_system/typecheck_module.cc, xls/dslx/type_system/typecheck_module_test.cc, xls/dslx/type_system/zip_types.cc, xls/public/c_api_dslx.cc
analogous (but more powerful than) import, e.g.
```
use std;
```
and
```
use path::to::my_module;
```
Then we can colon-ref off of that module name.
The type of a module reference is an existential wrapper of the module identity itself. This lets us keep type information for the AST node in the TypeInfo mapping without having a "hole" where an AST node has no associated type information.
Implementation-wise this mostly means that `UseTreeEntry*` nodes have to ride the same pathways that `Import*` nodes were already riding in order to resolve module attributes.
=> [DSLX] `use` syntax: enable using a module.

xls/dslx/ir_convert/function_converter.cc, xls/dslx/ir_convert/ir_converter_test.cc, xls/dslx/ir_convert/testdata/ir_converter_test_MatchExhaustiveMultiplePatternLastArm.ir, xls/dslx/ir_convert/testdata/ir_converter_test_MatchExhaustiveOneRangeAndValueInSingleArm.ir, xls/dslx/ir_convert/testdata/ir_converter_test_MatchExhaustiveRangeInTrailingArm.ir
Previously we would give an IR conversion error, which was a vestige from where we needed the trailing arm to be a wildcard. Now with exhaustiveness we know the trailing match arm must be usable as a default case in the priority select that we lower to.
=> [DSLX:ir_conv] IR convert trailing match arms w/ multiple patterns.

xls/dslx/lsp/language_server_adapter.cc, xls/dslx/lsp/language_server_adapter_test.cc
It may be in a parametric function.
Previously this function would dump log spew into the LSP log.
=> [DSLX:LS] Do not flag an issue when there is not type information for a let binding

xls/dslx/fmt/ast_fmt.cc, xls/dslx/frontend/ast.cc, xls/dslx/frontend/ast.h, xls/dslx/tests/errors/error_modules_test.py, xls/dslx/tests/errors/logical_and_on_functions.x, xls/dslx/type_system/deduce_expr.cc, xls/dslx/type_system/typecheck_module_test.cc, xls/dslx/type_system_v2/typecheck_module_v2.cc
Previously this sample would give an internal error because it would try to diff two function types. However, the real error we want to present here is that the operator cannot be used on function types at all, instead of trying to diff the function types.
=> [DSLX:TS] Give non-internal error when using binops on functions.

docs_src/dslx_language_server.md
Verible commit https://github.com/chipsalliance/verible/commit/877f60da6535d50945b6bfb4aeaeaaec1e5feea1 moved some paths around, breaking links.
@hzeller
=> [docs] Fix verible links in LSP docs.

xls/data_structures/inline_bitmap.h, xls/dslx/tests/quickcheck_fn_with_fail.x, xls/ir/value.cc, xls/ir/value_test.cc
Previously we would refuse to populate a token if it was in the signature.
=> [DSLX] Allow exhaustive quickchecks to target implicit-token-calling-convention

xls/dslx/frontend/ast_utils.cc, xls/dslx/frontend/ast_utils.h, xls/dslx/frontend/builtins_metadata.cc, xls/dslx/frontend/builtins_metadata.h, xls/dslx/tests/BUILD, xls/dslx/tests/test_assert_helper.x, xls/dslx/type_system/deduce_invocation.cc, xls/dslx/type_system/typecheck_invocation.cc, xls/fuzzer/sample_generator.cc
Observed doing `--compare=jit` where there were helper functions for test scaffolding.
Previously the metadata that `assert_eq` requires an implicit token calling convention was not properly reflected. Organized some of the builtins metadata in the process since having the strings embedded into the deduce function is non ideal.
=> [DSLX] Fix IR conversion when helper functions are used to do `assert_eq`

xls/codegen/block_generator.cc, xls/codegen/block_generator_test.cc, xls/codegen/testdata/block_generator_test_MultiProcNoDataDirectConnect.vtxt, xls/codegen/testdata/block_generator_test_MultiProcWithInternalNoDataFifo.vtxt
Since verilog does not allow zero-width channels or parametric removal of module I/O, a FIFO with zero data cannot be (ergonomically) implemented by parameterizing the general "with data" FIFO.
Update the block generator to generate instantiations of `xls_nodata_fifo_wrapper` instead of `xls_fifo_wrapper` in this case.
Also add test cases that exercise this instantiation.
---
*Note:*
ATM the tests are just copies of the other two fifo block generator tests with small adjustments. I looked into parameterizing the tests with fifo width so the same ones can be used, but because the tests already use the parametric `VerilogTestBase ` (which selects different simulation targets) I don't see a clean and simple way of doing this?
=> Generate `nodata` fifo wrapper for FIFOs with width 0.

xls/public/BUILD, xls/public/c_api.cc, xls/public/c_api.h, xls/public/c_api_impl_helpers.cc, xls/public/c_api_symbols.txt, xls/public/c_api_test.cc
Note that `xls_value_from_bits` erroneously moved out of the const ref before and that's fixed in this PR (I didn't know you could even do that).
=> [c_api] Expose function JIT facilities (used in xlsynth crate)

xls/codegen/fifo_model_test_utils.h, xls/codegen/materialize_fifos_pass.cc, xls/codegen/materialize_fifos_pass_test.cc, xls/interpreter/block_interpreter.cc, xls/ir/instantiation.cc
Gates the generation of the FIFO "data path" behind a non-zero data width and adjusts the signature accordingly.
Materializing channels with a zero-width data path fails due to mismatching signatures.
buf.x:
```rust
proc Nop {
input: chan<()> in;
output: chan<()> out;
init { () }
config(input: chan<()> in, output: chan<()> out) {
(input, output)
}
next(_: ()) {
let (tok, v) = recv(join(), input);
send(tok, output, v);
}
}
proc Top {
input: chan<()> in;
output: chan<()> out;
init { () }
config(input: chan<()> in, output: chan<()> out) {
let (s, r) = chan<(), u32:1>("between");
spawn Nop(input, s);
spawn Nop(r, output);
(input, output)
}
next(_: ()) { }
}
```
Run: 
```bash
./bazel-bin/xls/dslx/ir_convert/ir_converter_main ./buf.x > buf.ir
./bazel-bin/xls/tools/opt_main ./buf.ir …
```
=> Correctly materialize zero-width FIFOs.

xls/contrib/mlir/IR/xls_ops.cc, xls/contrib/mlir/IR/xls_ops.td, xls/contrib/mlir/testdata/array_to_bits.mlir, xls/contrib/mlir/testdata/index_type_conversion.mlir, xls/contrib/mlir/testdata/proc_elaboration.mlir, xls/contrib/mlir/testdata/translate_chn.mlir, xls/contrib/mlir/testdata/translate_from_xls/proc.ir, xls/contrib/mlir/tools/xls_translate/xls_translate_from_mlir.cc, xls/contrib/mlir/tools/xls_translate/xls_translate_to_mlir.cc, xls/contrib/mlir/transforms/array_to_bits.cc, xls/contrib/mlir/transforms/index_type_conversion.cc, xls/contrib/mlir/transforms/proc_elaboration.cc, xls/contrib/mlir/transforms/scalarize.cc
As discussed via email.
Support XLS fifo properties/config in MLIR channels.
This also adds support for converting these properties to/from XLS, and updates different passes (array_to_bits, index_type_conversion) to ensure these attributes are maintained when channels are modified.
Finally, these properties are also exposed for sproc channels, and the proc elaboration pass is updated to assign said properties to all eproc channels that are generated from an sproc channel.
To be discussed: Are the input/output flopping fifo configuration values required?
=> [xls][mlir] Support XLS fifo properties/config in MLIR channels.

xls/codegen/block_stitching_pass_test.cc, xls/codegen/fifo_model_test_utils.h, xls/codegen/materialize_fifos_pass.cc, xls/interpreter/block_evaluator_test_base.h, xls/interpreter/block_interpreter.cc, xls/ir/channel.h
Replace distributed (and inconsistent) checks for supported FIFO configs.
Fixes tests with unsupported FIFO configs.
---
As mentioned in https://github.com/google/xls/pull/1896.
I assume the mismatch here is because they got out of sync, and not because of different requirements.
Note that, because the checks were inconsistent and there is little documentation on the purpose of these restrictions, I took the union/most restrictive set.
Also it would be helpful to add documentation/comments to the `isSupported` function that explain these limits. I don't quite know where they come from  :)
I assume that @allight and @grebe are responsible here. Thanks! :)
=> Centralize definition/validation of supported FIFO config.

xls/public/c_api_symbols.txt, xls/public/c_api_test.cc, xls/public/c_api_vast.cc, xls/public/c_api_vast.h, xls/public/c_api_vast_test.cc
Was required by the xlsynth-crate but it had not been added (lazy loaded symbols hid the fact it was missing): https://github.com/xlsynth/xlsynth-crate/blob/6632f31907f30ad9f51c56ab4301cea90e6b59a5/xlsynth/src/vast.rs#L132
`$ bazel test -c opt --config=asan --action_env=ASAN_OPTIONS=detect_odr_violation=0 //xls/public/...` tested cleanly
=> [c_api:vast] Add missing xls_vast_index_as_expression

README.md, docs_src/README.md
The new `./xls/dev_tools/make-compilation-db.sh` generates a `compile_flags.txt` file.
@hzeller
=> Remove references to `compile_commands.json` in documentation.

xls/ir/verifier_test.cc, xls/ir/verify_node.cc
Previously we would not flag that one hot sel and prio sel had type inconsistency among their cases (i.e. even when verify arg was given as true to the builder).
=> [IR] Add case type verification for OneHotSel and PrioritySel

xls/dev_tools/check_ir_equivalence_main.cc, xls/dev_tools/check_ir_equivalence_main_test.py
Previously this would segfault.
Also adds pylint to the pre-commit yaml; this effectively fixes #1986 as we will now see pylint errors via the pre-commit hook
=> [dev_tools] Flag when a package has no top in `check_ir_equivalence_main`.

xls/contrib/mlir/IR/xls_ops.td, xls/contrib/mlir/testdata/debug_locs.mlir, xls/contrib/mlir/testdata/translate_from_xls/proc.ir, xls/contrib/mlir/tools/xls_translate/xls_translate_from_mlir.cc, xls/contrib/mlir/tools/xls_translate/xls_translate_to_mlir.cc
As noted in https://github.com/google/xls/pull/1916, I was not able to easily add a round-trip test for channel attributes due to some issues with debug locations in `xls_translate`. 
While fixing this, I wanted to verify that round-trip conversion worked by smoke testing with `ops_translate.mlir`, where I noticed that my xls->mlir translation did not support `trace` and that my naming of the fifo flop kind enum was inconsistent.
---
Poping the stack, this PR contains the following commits addressing all of the above:
Makes it consistent with all other values in XLS MLIR assembly.
`xls_translate` previously assigned an ID to every source file encountered in the MLIR `Location` of input ops and referenced these IDs in the XLS `pos` attribute of the produced IR nodes, but did not actually …
=> [xls][mlir] Fix emission of  debug locations in `xls_translate`

xls/contrib/mlir/testdata/ch_attrs.mlir, xls/contrib/mlir/testdata/ops_translate.mlir
Contains:
`[xls][mlir] Add round-trip conversion test for channel properties`:
This was previously not easily possible due to the incorrect emission of XLS file locations in `xls_translate`.
`[xls][mlir] Expand `ops_translate.mlir` test to round-trip verification.`
@jpienaar 
:warning: CI will not pass (and this should not be merged) until both https://github.com/google/xls/pull/1992 and https://github.com/google/xls/pull/2004 are merged :warning:
=> [xls][mlir] Expand round-trip testing

xls/public/BUILD, xls/public/c_api.h
This seems required for OS X builds to link the artifact -- not sure why it wasn't required on other platforms, maybe there's some different per-object-artifact culling.
=> [c_api] Add ir builder target to `:c_api` as dep and header to `c_api.h`.

xls/codegen/block_conversion.cc, xls/codegen/block_stitching_pass.cc, xls/codegen/block_stitching_pass_test.cc, xls/codegen/clone_nodes_into_block_handler.cc, xls/codegen/codegen_checker.cc, xls/codegen/codegen_pass.cc, xls/codegen/codegen_pass.h, xls/codegen/conversion_utils.cc, xls/codegen/proc_block_conversion.cc, xls/codegen/ram_rewrite_pass.cc
This will make it much easier to transition from bag-on-the-side metadata to metadata on the IR.
=> Encapsulate some codegen metadata data structures as classes.

docs_src/ir_semantics.md
See the node definition https://sourcegraph.com/github.com/google/xls@8a3b8b0a7b4fbfce6f6d428c9d6c9c4f8f63f6f0/-/blob/xls/ir/nodes.h?L484 and the IR parser which parses it as a normal unary op: https://sourcegraph.com/github.com/google/xls/-/blob/xls/ir/ir_parser.cc?L1017
(This may have been a copy pasta from `decode`)
=> [docs] Fix docs for encode IR op, it does not take a width attribute.

xls/fuzzer/sample.cc
Introduced in https://github.com/google/xls/commit/adcc9707cc4c0ef1eaf6264144d34c0ea8463e5c
@grebe
=> Adapt fuzzer known failure regex to new error message format.

xls/dslx/stdlib/BUILD, xls/dslx/stdlib/abs_diff.x
Absolute difference is a key calculation in e.g. floating point exponent comparison.
=> [DSLX:stdlib] Add absolute difference module to stdlib.

xls/fuzzer/sample_generator_test.cc
The test `GenerateBasicProcSample` asserted that the proc generated does not feature any channels. This is the case for the (fixed) default seed but not true in general. For example, a seed of `4` causes the test to fail:
```cpp
std::mt19937_64 rng(4);
```
This removes the seed-dependent assertions.
Also explicitly set the sample type to `proc`, instead of the default (unknown).
Pinging @hzeller since you added these assertions :)
=> Fix seed-dependent proc sample generator test.

docs_src/dslx_std.md, xls/dslx/stdlib/std.x
Where `n` is variable, there are many suboptimal ways to do this; to guide users to more efficient implementations, we provide stdlib functions `std::mask_lsbs` and `std::mask_msbs`, along with their complements `std::without_lsbs` and `std::without_msbs`.
=> [stdlib] Add new functions for extracting the `n` LSBs/MSBs from a value

xls/fuzzer/ast_generator.cc
This is one of the cause of https://github.com/google/xls/issues/1140.
A token produced by a send, passed through a counted_for, and then consumed by a receive would not correctly increase the `min_stage`. For example, the following would incorrectly report a min pipeline stages of 1:
```rust
let x3: token = send(join(), x0, u1:1);
let x4: token = for (i, x) in u4:0x0..u4:0x8 {
x
}(x3);
let x5: (token, u37, bool) = recv_non_blocking(x4, x1, u37:45812984490);
```
Not sure if there are other reasons for https://github.com/google/xls/issues/1140 or if the `known_failure` can be removed?
Edit: Still seems to happen - 1140 not resolved.
=> Fuzzer: Correctly propagate pipeline info through counted-fors

xls/fuzzer/run_crasher.cc, xls/fuzzer/run_fuzz.cc, xls/fuzzer/run_fuzz.h, xls/fuzzer/run_fuzz_codegen_test.cc, xls/fuzzer/run_fuzz_multiprocess.cc, xls/fuzzer/run_fuzz_test.cc, xls/fuzzer/sample_runner.cc, xls/fuzzer/sample_runner.h, xls/fuzzer/sample_runner_main.cc
While working on fuzzer stuff, I found it useful to track the actual rate of skipped/`known_failure` samples generated. This adds bookkeeping to count the total number of samples, skipped samples, and crashes. The multiproc runner is updated to accumulate these statistics from all workers and print the totals.
=> fuzzer: gather total crashers and skipped sample stats.

README.md, docs_src/README.md
Removes links that are broken and, from my understanding, no longer relevant:
- `docs`: Generated docs are no longer checked-in.
- `uncore_rtl`: Seems to not be super relevant anymore (has been moved to `contrib/ice40/uncore_rtl`)
=> Remove dead links from README/docs.

xls/dslx/stdlib/BUILD
This PR adds a `acm_random_dslx` DSLX library to enable pulling this module into other designs.
It is required for merging #1857.
CC @proppy
=> dslx/stdlib: Add missing acm_random DSLX library

xls/dslx/bytecode/BUILD, xls/dslx/bytecode/builtins.cc, xls/dslx/bytecode/builtins.h, xls/dslx/bytecode/bytecode_interpreter.cc, xls/dslx/bytecode/proc_hierarchy_interpreter_test.cc
This PR contains the changes requested in  https://github.com/google/xls/issues/1874, that add printing proc hierarchy in assertions and fail! macro. Here are some error messages shouwing the final result:
1. `assert` in a hierarchy:
```[ RUN UNITTEST  ] TestAssertInHierarchy
xls/examples/assert.x:39:16-39:43
0037:     next(state: ()) {
0038:         let (tok, predicate) = recv(join(), req_r);
0039:         assert!(predicate, "assert_label");
~~~~~~~~~~~~~~~~~~~~~^-------------------------^ FailureError: The program being interpreted failed! assert_label (called from TestAssertInHierarchy->Assert:7)
0040:         send(tok, resp_s, ());
0041:     }
[        FAILED ] TestAssertInHierarchy
```
2. `assert` directly in a test
```
[ RUN UNITTEST  ] TestAssert
xls/examples/assert.x:75:16-75:39 …
```
=> Distinguish sources of asserts in a proc chain

xls/contrib/mlir/tools/xls_translate/xls_translate_to_mlir.cc
The builders already contain the context that can be accessed if required.
Thanks @jpienaar for the suggestion.
=> [xls][mlir] Remove redundant `MLIRContext*` parameters.

docs_src/dslx_std.md
* Fix a few spelling errors, and other typos
* Consistency: DSLX
* comma after e.g. and i.e.
* hyphenation where needed
=> [DSLX:doc] Formatting, spelling, and other minor improvements

xls/dslx/diagnostics/maybe_explain_error.cc, xls/dslx/diagnostics/maybe_explain_error_test.cc, xls/dslx/fmt/ast_fmt.cc, xls/dslx/fmt/ast_fmt_test.cc, xls/dslx/frontend/ast.cc, xls/dslx/frontend/ast.h, xls/dslx/frontend/ast_cloner.cc, xls/dslx/frontend/parser.cc, xls/dslx/frontend/parser_test.cc, xls/dslx/tests/errors/error_modules_test.py, xls/dslx/tests/errors/if_without_else_returning_mismatching_type.x
This PR addresses the changes requested in #1980, enabling the use of `if` expressions without requiring an `else` branch. Additionally, it provides more detailed error messages for failing cases, helping users better understand potential issues with their code. The error message is taken from the rust compiler and resembles the one posted in the issue description (https://github.com/google/xls/issues/1980#issue-2899942121)
Here is an example of the error message, which provides explanation to the user:
* Incorrect DSLX code:
```rust
fn if_without_else_incorrect (predicate: bool) {
if (predicate) {
trace_fmt!("This is if with else (if branch)")
}
}
#[test]
fn test_if_without_else_incorrect() {
assert_eq(if_without_else_incorrect(true), ());
assert_eq(if_without_else_incorrect(false), ()); …
```
=>  Allow if without else in DSLX

xls/common/math_util_test.cc, xls/data_structures/binary_decision_diagram_test.cc, xls/dslx/bytecode/bytecode_interpreter_test.cc, xls/dslx/stdlib/tests/umul_with_overflow_long_test.cc, xls/dslx/type_system/deduce_utils.cc, xls/estimators/delay_model/delay_estimator.cc, xls/ir/function_builder.cc, xls/ir/verify_node.cc, xls/passes/resource_sharing_pass.cc, xls/tests/basic_ir_ops_test.cc
This was breaking the OS X build on integrate from upstream.
I think the recommendation in the style guide is to avoid integer type suffxes but they can easily creep in since there's not a tidy for them.
=> [cleanup] Switch uses of L and LL suffixes to be explicitly typed for x-platform portability

xls/dslx/type_system_v2/type_annotation_utils.cc
This caused issues with the macOS build in github actions which uses an older Clang / macOS compatible version.
=> [cleanup] Switch SignednessAndBitCountResult instantiation to use initializer syntax

docs_src/dslx_std.md, xls/dslx/stdlib/std.x
- Add saturating subtraction for unsigned arguments and unsigned result.
- bounded_minus_1 now uses sat_sub
- Replace assert in {split_msbs, split_lsbs} with const_assert. This matches the original intention: ensures well-formed type-level arguments.
=> [DSLX, stdlib] add sat_sub, prefer const_assert

xls/ir/node.h
Per review discussion in https://github.com/google/xls/pull/2251 the `BitCountOrDie` method on Node assumes the result type for the node is `BitsType` which is convenient as we have a lot of things like that, but it also obscures the assumption cases where the result may not be `BitsType`.
Put a good comment at least to indicate the precondition and upside/downside.
cc @proppy
=> [cleanup] Make a comment on BitCountOrDie in Node.

xls/public/xls_public_macros.oss.bzl
(Without this the macOS dylib build exports all symbols.)
Upstreaming to minimize downstream divergence.
=> [macOS] Only export intended symbols.

xls/ir/verifier_test.cc, xls/ir/verify_node.cc, xls/jit/function_jit_test.cc
* non-equality cmp comparisons (ult, slt, etc.) now strictly require `bits` type operands, aligning verifier with `ir_semantics.md`
*  equality comparisons (eq, ne) now disallow `Token` type operands in the verifier
=> [ir] strict verification for comparison operations

docs_src/codegen_options.md, xls/codegen/BUILD, xls/codegen/block_conversion.cc, xls/codegen/block_generator_test.cc, xls/codegen/block_inlining_pass_test.cc, xls/codegen/codegen_options.cc, xls/codegen/codegen_options.h, xls/codegen/codegen_pass.h, xls/codegen/combinational_generator.cc, xls/codegen/conversion_utils.cc, xls/codegen/mark_channel_fifos_pass_test.cc, xls/codegen/maybe_materialize_fifos_pass_test.cc, xls/codegen/name_legalization_pass_test.cc, xls/codegen/passes_ng/stage_conversion_pass_pipeline_test.cc, xls/codegen/pipeline_generator.cc, xls/codegen/priority_select_reduction_pass.cc, xls/codegen/priority_select_reduction_pass_test.cc, xls/codegen/ram_rewrite_pass_test.cc, xls/codegen/register_chaining_analysis_test.cc, xls/codegen/side_effect_condition_pass_test.cc, xls/codegen/trace_verbosity_pass_test.cc, xls/codegen/unified_generator.cc, xls/jit/block_jit.cc, xls/tools/codegen.cc, xls/tools/codegen_flags.cc, xls/tools/codegen_flags.h, xls/tools/codegen_flags.proto, xls/tools/codegen_main_test.py
Sometimes passes want to add in assertions for properties they "believe they have proven to be true but would like additional validation for at simulation-time".
We put these assertions behind a flag because they can slow down assert-condition coverage closure.
=> [codegen] flag to avoid inserting "invariant assertions" via codegen passes

xls/common/exit_status.cc, xls/dslx/dslx_fmt.cc, xls/dslx/dslx_fmt_test.py, xls/dslx/interpreter_test.py
If dslx_fmt encounters a positional error in parsing the module print it in human-readable form.
=> [dslx:fmt] Print human readable positional (scan/parse) errors

dependency_support/llvm/workspace.bzl, dependency_support/llvm/zlib-header.patch
The includes of zlib in the llvm-project uses angle brackets instead of double-quotes implying to pick the system header instead of the one provided by the BUILD context.
If the zlib header is not installed on the system, this resulted in a build-breakage for me.
Add a patch to the llvm toolchain to fix the files using the wrong quotes.
=> Make sure the llvm-build does not pick up the system zlib header.

xls/dslx/frontend/builtin_stubs_utils.h
Otherwise clang complains that it is not used right there in the header.
=> Mark a globally visible constexpr as inline constexpr

xls/dslx/type_system_v2/type_system_tracer.h
Forward-declaring a `struct` type as `class` might or might not work.
=> Change forward declaration of a `struct` (was `class`)

xls/dev_tools/check_cpp_includes.py, xls/dslx/stdlib/apfloat.x, xls/dslx/stdlib/tests/BUILD, xls/dslx/stdlib/tests/bfloat16_cmp_test.cc, xls/ir/bits.cc, xls/ir/bits.h
Fixes `+0 > -0`, it used to give `true` and now appropriately gives `false` -- this fixes google/xls#2448
Adds a missing `Bits::ToBool()` helper analogous to `ToUint64()`
Adds more comprehensive testing vs the Eigen bfloat16 implementation:
* exhaustive 16-bit vs interesting
* 2**20 randomized
=> [dslx:stdlib] Add comprehensive apfloat cmp testing via bfloat16

xls/dev_tools/make-compilation-db.sh
A bunch of files include generated files (in particular gentbl), which would be missing if `clang-tidy` or `clangd` ran over a fresh checkout. Make sure all the relevant artifacts are produced.
=> Update compilation-db generation to build more relevant artifacts.

.pre-commit-config.yaml, xls/dslx/interpreter_test.py
Ran `$ python3 -m yapf --style="{based_on_style: google, indent_width: 2}" -i xls/dslx/interpreter_test.py` to try to get style compliant
=> [dslx] Add an out-of-tree interpreter test to regression test the usecase

docs_src/tutorials/how_to_use_procs.md, xls/dslx/bytecode/bytecode_interpreter.cc, xls/dslx/errors.cc, xls/dslx/errors.h, xls/dslx/fmt/ast_fmt.cc, xls/dslx/fmt/ast_fmt_test.cc, xls/dslx/frontend/ast_cloner.cc, xls/dslx/frontend/parser.cc, xls/dslx/frontend/parser.h, xls/dslx/frontend/parser_test.cc, xls/dslx/frontend/proc.cc, xls/dslx/frontend/proc.h, xls/dslx/run_routines/run_routines.cc, xls/dslx/run_routines/run_routines_test.cc
This commit introduces the ability to specify that a test proc is expected to fail on a particular `assert!` or `fail!` in the DSLX interpreter. The `#[test_proc]` attribute accepts an optional `expected_fail` parameter. with the label marking the failure. If a failure occurs with the matching label, the test is treated as successful.
The choice to implement this as an attribute, rather than a built-in, as discussed in https://github.com/google/xls/issues/1071#issuecomment-1642453871 was motivated by cases where there's no clear location to “catch” the failure. For example, a test that spawns a proc containing only a single `fail!` statement.
The functionality is implemented by storing the `expected_fail` value in the `TestProc` object. When an `assert!` or `fail!` is handled in the DSLX …
=> Allow #[test_proc] to expect specific assertion failures

xls/codegen/vast/translate_vast_to_dslx.cc, xls/dslx/bytecode/bytecode_interpreter.cc, xls/dslx/bytecode/bytecode_interpreter_test.cc, xls/dslx/fmt/BUILD, xls/dslx/fmt/ast_fmt.cc, xls/dslx/fmt/ast_fmt.h, xls/dslx/fmt/ast_fmt_test.cc, xls/dslx/frontend/ast.cc, xls/dslx/frontend/ast.h, xls/dslx/frontend/ast_cloner.cc, xls/dslx/frontend/ast_test.cc, xls/dslx/frontend/ast_utils.h, xls/dslx/frontend/module.h, xls/dslx/frontend/parser.cc, xls/dslx/frontend/parser.h, xls/dslx/frontend/parser_test.cc, xls/dslx/frontend/proc.cc, xls/dslx/frontend/proc.h, xls/dslx/frontend/proc_test_utils.cc, xls/dslx/ir_convert/extract_conversion_order.cc, xls/dslx/ir_convert/extract_conversion_order.h, xls/dslx/ir_convert/extract_conversion_order_test.cc, xls/dslx/ir_convert/ir_converter.cc, xls/dslx/ir_convert/ir_converter_test.cc, xls/dslx/ir_convert/testdata/ir_converter_test_ConvertWithTests.ir, xls/dslx/ir_convert/testdata/ir_converter_test_ConvertWithoutTests.ir, xls/dslx/type_system/deduce_utils_test.cc, xls/fuzzer/ast_generator.cc
This commit adds a `#[cfg(test)]` attribute that you can use to mark functions or procs that are only meant for testing. When marked this way, they won't be lowered to IR.  The original request in #1524 was just for functions, but I applied the same idea to procs as well.
This feature uses a `test_only` flag in the `Function` class to mark functions and procs that are only used for tests. When converting code to IR, functions and procs  marked as test-only are skipped, unless the `convert_tests` option is enabled. This allows test helpers to be included in the IR if needed.
IR conversion now provides clearer error messages. If a test-only function or proc is selected for conversion without the `convert_tests` option, a dedicated error is shown. Same happens when a test-only function is …
=> Add support for #[cfg(test)] attribute

xls/passes/BUILD, xls/passes/basic_simplification_pass.cc, xls/passes/basic_simplification_pass_test.cc
If a value appears as an operand to a XOR an even number of times, the operands are removed. If the value appears an odd number of times the operands are replaced with a single instance of the value.
=> Optimize duplicate operands in XOR operations.

xls/dslx/cpp_transpiler/cpp_type_generator.cc, xls/dslx/cpp_transpiler/testdata/BasicEnums.htxt, xls/dslx/cpp_transpiler/testdata/BasicTypedefs.htxt, xls/dslx/cpp_transpiler/testdata/EnumWithConstexprValues.htxt, xls/dslx/cpp_transpiler/testdata/EnumWithS64.htxt, xls/dslx/cpp_transpiler/testdata/EnumWithU64.htxt, xls/dslx/cpp_transpiler/testdata/HandlesAbsolutePaths.htxt, xls/dslx/frontend/BUILD
This way, they won't be reported as unused values warnings.
=> Use `inline constexpr` for toplevel constants in headers.

MODULE.bazel.lock, dependency_support/rules_hdl/workspace.bzl
This new version of rules hdl has more sources listed for the ncurses dep which should make build breakages due to failed downloads less common.
=> Update version of rules_hdl

xls/dslx/frontend/builtins_metadata.cc, xls/dslx/frontend/builtins_metadata.h, xls/dslx/frontend/parser.cc, xls/dslx/frontend/parser_test.cc
Preivously this would cause an internal TypeMissing error:
```
[cdleary@cdleary-devbox-ng ~/proj/xlsynth (main)] 2025-08-19 12:23:23
$ bazel-bin/xls/dslx/interpreter_main /tmp/sample.x 
/tmp/sample.x:2:5-2:15
0001: fn main() {
0002:     trace_fmt!<>;
~~~~~~~~~~^--------^ TypeMissingError: node: 0x5c5184ec7f70 user: 0x5c5184e7ced0 internal error: AST node is missing a corresponding type: trace_fmt! 0x5c5184ec7f70 (kind: BuiltinNameDef) defined @ <no span>. This may be due to recursion, which is not supported.
0003:   }
[cdleary@cdleary-devbox-ng ~/proj/xlsynth (main)] 2025-08-19 12:24:22
$ cat /tmp/sample.x 
fn main() {
trace_fmt!<>;
}
```
This was triggering because a malformed trace_fmt!<> with explicit parametrics slipped past parsing as a generic invocation, so the builtin callee never …
=> [DSLX:FE] Fix for instantiation of builtin trace_fmt!

xls/dslx/frontend/parser.cc, xls/dslx/frontend/parser_test.cc
Previously, ParsePattern treated any type keyword as the start of a numeric literal, so `match 0 { type` attempted number parsing and failed with a confusing `INVALID_ARGUMENT: "String is not a BuiltinType: \"type\""`. This change excludes type from the number-start detection in ParsePattern, so it now yields a clear parse error: "Expected pattern; got keyword:type". Added a targeted parser test to lock in the behavior.
=> [DSLX:FE] Fix internal error for type keyword in match pattern position.

BUILD, CONTRIBUTING.md, MODULE.bazel, README.md
Use hedronvision/bazel-compile-commands-extractor to generate the
compile_commands.json file. This file is used by clangd for autocomplete
and other IDE featues. This approach is more robust than the existing
dev_tools/make-compilation-db.sh approach and results with many fewer
error/warning false positives being flagged in the UI (unused includes,
undefined symbols, etc).
As configured the json file is large (70MB) but not enormous and does not
seem to pose problems for clangd.
=> Add support for generating compile_commands.json.

xls/codegen/BUILD, xls/codegen/block_generator.cc, xls/codegen/block_generator.h, xls/codegen/codegen_options.cc, xls/codegen/codegen_options.h, xls/codegen/codegen_residual_data.proto, xls/codegen/codegen_result.h, xls/codegen/combinational_generator.cc, xls/codegen/pipeline_generator.cc, xls/codegen/unified_generator.cc, xls/fdo/BUILD, xls/fdo/synthesizer.cc, xls/ir/topo_sort.cc, xls/ir/topo_sort.h, xls/ir/topo_sort_test.cc, xls/tools/BUILD, xls/tools/block_to_verilog_main.cc, xls/tools/block_to_verilog_main_test.py, xls/tools/codegen.cc, xls/tools/codegen_flags.cc, xls/tools/codegen_flags.h, xls/tools/codegen_flags.proto, xls/tools/codegen_main.cc, xls/tools/codegen_main_test.py
This residual data currently just includes the emission order of the nodes into verilog though it will likely expand. It can be consumed in later codegen processes to reuse the emission order and minimize the differences in the generated Verilog. For example if you dump the residual metadata from IR sample A and use it for codegen'ing IR sample A' (small diff from A) then the resulting verilog from A' will have a very similar emission order assuming a correspondence of node ids between A and A'.
=> Create and save residual metadata from codegen

docs_src/tutorials/intro_to_parametrics.md
added missing `()` that causes error:
`Expected '(', got '{'DSLX`
=> Fix code block inside intro_to_parametrics.md

xls/passes/concat_simplification_pass.cc, xls/passes/concat_simplification_pass_test.cc
This PR introduces an optimization that hoists bitwise operations (`AND`, `OR`, `XOR`) above `Concat` nodes when one of the `Concat` operands is a constant `0...0` or `1...1`. This narrowing transformation reduces the operand width of the bitwise operation, potentially reducing logic utilization and improving performance.
This fixes the open issues:
- **#1217**: Redundant wide bitwise ops after concat
- **#1218**: Missed opportunity to narrow XORs over concat with zero bits
Note that I have left out the case of XORs with concat operands that concatenate with constant 1s. This case is not implemented because it would consume additional hardware for the negation compared to other cases implemented in this pass and likely would need more scrutiny before implementing.
In addition to the …
=> Narrowing bitwise operators around concats with constant literal 0s or 1s
