docs_src/ir_semantics.md

Rebase of https://github.com/google/xls/pull/94 onto HEAD

Rebase of "Add documentation to ir_semantics.md for dynamic_bit_slice op #94"

---

xls/examples/jpeg/BUILD
xls/examples/jpeg/idct_chen.x

Implemented as composition of 8-point 1D IDCTs.
(Originally PR, accidentally closed, is in https://github.com/google/xls/pull/80 )

2D IDCT (8x8) algorithm implementation in DSL.

---

docs_src/ir_semantics.md
xls/codegen/node_expressions.cc
xls/interpreter/ir_interpreter.cc
xls/interpreter/ir_interpreter.h
xls/ir/BUILD
xls/ir/abstract_node_evaluator.h
xls/ir/dfs_visitor.cc
xls/ir/dfs_visitor.h
xls/ir/function_builder.cc
xls/ir/function_builder.h
xls/ir/function_builder_test.cc
xls/ir/ir_matcher.cc
xls/ir/ir_matcher.h
xls/ir/ir_parser.cc
xls/ir/node.cc
xls/ir/nodes_source.tmpl
xls/ir/op_specification.py
xls/ir/verifier.cc
xls/ir/verifier_test.cc
xls/passes/bdd_function.cc

This is like CountedFor, except that the trip count and stride are dynamic. Plumbing has been added along with some implementation components (function builder, ir matcher, parser, verifier).

Adding DynamicCountedFor op to the IR.

---

xls/synthesis/BUILD
xls/synthesis/timing_characterization_client_main.py

Hi, 
based on previous @cdleary work, I slightly extended the amount of supported operations.
The code is mostly to start a conversation on which different estimators, and parameter space we should sample for each operation.
Let me know what you think.
-l

Extended ice40 supported operations characterization

---

README.md
xls/examples/cubic_bezier.x

In the meantime, I will try to port the following (not-yet) test case to your testing system.
https://github.com/lromor/beagleg-fpga-backend/blob/bezier/sim/cubic-bezier_test.cc

Cubic bezier example.

---

xls/dslx/stdlib/apfloat.x
xls/dslx/stdlib/bfloat16.x
xls/dslx/stdlib/float32.x
xls/dslx/stdlib/float64.x
xls/dslx/tests/local_const_value_as_nested_loop_bound.x
xls/examples/BUILD
xls/examples/dot_product.x
xls/examples/fir_filter.x

Also added int-to-floating-poinnt casting.

Added dot product and fir-filter examples.

---

xls/examples/hack_cpu.x

- 2 space indent
- remove tabs

[examples/hack_cpu] fix formatting

---

xls/examples/riscv_simple.x

- replace binary-op with slice expr
- fix `decode_j_instruction` `imm_10_1` length
- use consistent indentation
- split bits nibble with `_`
- remove usused `waddr` function

[example/riscv] use bit slice expr

---

xls/dslx/ir_converter_main.cc

Similar to what the other tools already support:
https://github.com/google/xls/search?q=%2Fdev%2Fstdin

dslx/ir_converter_main: resolve '-' as stdin

---

xls/delay_model/models/sky130.textproto

Fixes #806 
@vincent-mirian-google should we have a warning/note about the model not being accurate?

delay_model/sky130: alias onehot to or

---

README.md

README: add colab link

---

xls/common/file/filesystem_test.cc
xls/common/file/get_runfile_path.cc

On OS X, `/proc/self/exe` doesn't exist and the executable path is discovered via `_NSGetExecutablePath()`. This functionality used to be handled by `GetRealPath()` with a default argument- this change splits this out into a standalone function.
Also, on OS X temp directories are generally symlinks. Rather than comparing paths in the test, check `std::filesystem::equivalent()`.

Make filesystem stuff more portable.

---

WORKSPACE
dependency_support/rules_hdl/workspace.bzl

Newer versions are needed to work on my new-ish Mac.

Bump deps.

---

README.md

- add badge
- add instructions
- reword "build from source" intro
/cc @cdleary

README: add conda package

---

.github/workflows/build-mkdocs-commit-html.yml
.github/workflows/nightly-fuzz.yml
.github/workflows/nightly-ubuntu-22.04.yml
.github/workflows/one-bazel-test-ubuntu-20.04.yml
.github/workflows/one-bazel-test-ubuntu-22.04.yml

- run on bigger runners
- enable disabled targets and tests
- remove cache cleanup

github/workflows: move all remaining jobs to bigger runners

---

xls/dslx/frontend/parser_test.cc
xls/dslx/frontend/scanner.cc

Found via coverage-guided fuzzing.

[DSLX:scanner] Unterminated char/string at EOF.

---

.github/workflows/continuous-integration.yml
.github/workflows/nightly-fuzz.yml
.github/workflows/nightly-macos.yml
.github/workflows/nightly-ubuntu-22.04.yml
.github/workflows/one-bazel-test-ubuntu-20.04.yml
.github/workflows/one-bazel-test-ubuntu-22.04.yml

- split macos build into a separate night workflow
- unify bazelisk version
- remove unused deps

clean up github workflows

---

dependency_support/initialize_external.bzl
dependency_support/rules_hdl/workspace.bzl
xls/contrib/xlscc/examples/BUILD
xls/delay_model/BUILD
xls/examples/BUILD

- bump rules_hdl
- update asap7 workspace name
- add 7zip dep

dependency_support/rules_hdl: bump revision

---

dev_utils/rebuild_golden_files.sh

Update `dev_utils/rebuild_golden_files.sh` to reflect changes made in fea0611
This pull request fixes #1220.

Fix rebuild golden files script failure

---

xls/examples/ram.x

Solves #1209. Writes on port0 should be done with data from request1, not request0.

Fix dual port simultaneous writes

---

docs_src/dslx_reference.md

-  `>>>` does not exist, remove it
- fix rendering of `||` and `|` operators

Fix dslx_reference, a few operator-related things

---

docs_src/dslx_reference.md

- introduce Grouping Expression
- add `(...)` to precedence table
- add concat operator to precedence table
- refine section on Block Expressions
Resolves some tasks in https://github.com/google/xls/issues/1293
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/xls/1298)

[DSLX reference] add to precedence table, grouping expression

---

xls/dslx/stdlib/std.x

- add `iterative_div_mod` based on https://github.com/google/xls/blob/fa7af6cbda69d02d2d50b28fa5d95f51fe8cdfb1/xls/ir/abstract_evaluator.h#L513-L581
- unify implementation with existing `iterative_div` function

dslx/stdlib: add iterative_div_mod

---

xls/passes/query_engine.h

This should fix https://github.com/google/xls/actions/runs/8573290500/job/23497685241

xls/passes/query_engine: fix missing macro

---

docs_src/dslx_std.md

corrections for a few minor discrepancies in the dslx standard library documentation

add send_if to docs, fix missing _ in receive_non_blocking

---

xls/dslx/frontend/ast.cc
xls/dslx/frontend/ast.h
xls/dslx/frontend/module.cc
xls/dslx/frontend/module.h
xls/dslx/frontend/proc.h
xls/dslx/lsp/BUILD
xls/dslx/lsp/dslx_ls.cc
xls/dslx/lsp/find_definition.cc
xls/dslx/lsp/find_definition.h
xls/dslx/lsp/language_server_adapter.cc
xls/dslx/lsp/language_server_adapter.h
xls/dslx/lsp/language_server_adapter_test.cc

Rebased version of https://github.com/google/xls/pull/1564

[DSLX:LS] Get go-to-definition working across files and add a test.

---

README.md
docs_src/README.md

This is very useful for development but the tool to generate it is hidden away.

Add note about compilation-database generation to README.md.

---

xls/public/c_api.cc
xls/public/c_api.h
xls/public/c_api_test.cc

[c_api] Add support for more VAST constructs: instantiation, slice, continuous assignment

---

docs_src/tools.md

Commit d05feba88d18add7360ca9092aeb367f6cdf823d moved the location of `ir_stats_main.cc`. This PR adjusts sources to changes.

Update `ir_stats_main.cc` reference

---

xls/dslx/type_system/deduce.cc
xls/dslx/type_system/type.cc
xls/dslx/type_system/type.h
xls/dslx/type_system/typecheck_module_test.cc

[DSLX:TS] Prevent fatal when FunctionRef needs deduction and is not a function type.

---

xls/codegen/vast/vast.cc
xls/codegen/vast/vast.h
xls/codegen/vast/vast_test.cc
xls/public/c_api_test.cc

This is useful in somewhat bespoke stitching scenarios.

[VAST] Add support for empty port connections.

---

.github/workflows/nightly-ubuntu-22.04.yml
dist/BUILD

Include the language server in the binary distribution tar.

---

xls/dslx/stdlib/std.x
xls/ir/value.cc
xls/ir/value_test.cc

[DSLX] Make lsb and msb in stdlib sign-parametric, fix fuzz failure.

---

xls/contrib/mlir/IR/xls_ops.cc
xls/contrib/mlir/IR/xls_ops.td
xls/contrib/mlir/testdata/canonicalize.mlir

```
tuple_index(tuple($x1, $x2, ...), index=N) = $xN
```

[xls][mlir] Add tuple_index(tuple()) canonicalization

---

xls/contrib/mlir/IR/xls_ops.cc
xls/contrib/mlir/IR/xls_ops.td

Checks the following basic invariants:
- Non-zero number of values/predicates
- All values have matching type
- Values type matches return type

[xls][mlir] Add verification to NextValue node

---

.gitignore
MODULE.bazel.lock

This follows the best practices outlined in https://bazel.build/external/lockfile#best-practices.

Check in MODULE.bazel.lock.

---

xls/dslx/frontend/builtin_stubs.x
xls/dslx/ir_convert/BUILD
xls/dslx/ir_convert/ir_converter_options_flags.cc
xls/dslx/ir_convert/ir_converter_options_flags_test.cc

I don't believe this will trigger the IFTTT.

[DSLX:ir_conv] Add forgotten flag and add unit test for it.

---

xls/dslx/run_routines/run_routines.cc
xls/dslx/run_routines/run_routines_test.cc

(IMO statuses should be SSA in general to avoid mishandling.)

[DSLX:RR] Fix status handling for parse-and-prove.

---

xls/public/c_api_ir_builder.cc
xls/public/c_api_ir_builder.h
xls/public/c_api_symbols.txt
xls/public/c_api_test.cc

<s>Requires #1977 to land / consider second commit in this PR as a diffbase</s> :heavy_check_mark:

[c_api] Add bit slicing, concat, and dynamic bit slicing.

---

xls/contrib/mlir/testdata/translate_from_xls/trace.ir
xls/contrib/mlir/tools/xls_translate/xls_translate_to_mlir.cc

[xls][mlir] Add xls->mlir translation of `trace` IR node

---

xls/contrib/mlir/BUILD
xls/contrib/mlir/tools/xls_mlir_lsp_server/xls_mlir_lsp_server.cc

See https://mlir.llvm.org/docs/Tools/MLIRLSP/#mlir-lsp-language-server--mlir-lsp-server
@jpienaar @jmolloy 
(I am sure you having something like this internally, but that is probably tied to many other projects)

[xls][mlir] Add MLIR LSP server specialization with relevant dialects

---

xls/dslx/stdlib/apfloat.x
xls/dslx/stdlib/bfloat16.x

Add TIE_TO_AWAY RoundStyle to apfloat.

---

xls/passes/arith_simplification_pass.cc
xls/passes/arith_simplification_pass_test.cc

One step from #2045 -- ran multiprocess fuzzer for an hour.

[opt] add() elimination for sign-extend plus literal.

---

xls/dslx/stdlib/fixed_point.x

[DSLX] update fixed_point::sub to perform proper bit growth, closes https://github.com/google/xls/issues/2212

[DSLX] update fixed_point::sub to perform proper bit growth

---

xls/dslx/frontend/ast_utils.cc
xls/dslx/frontend/ast_utils.h
xls/dslx/tests/BUILD
xls/dslx/tests/match_tuple_concat_inference.x
xls/dslx/type_system_v2/inference_table_converter_impl.cc

[dslx:tiv2] Process match arms containing invocations first.

---

xls/dev_tools/make-compilation-db.sh

Build precondition for compilation DB even if there are build issues.

---

xls/dslx/ir_convert/function_converter.cc
xls/dslx/ir_convert/ir_converter_test.cc

[dslx:ir_convert] Fix overly aggressive renaming that propagated to parameters
